// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: code/Proto/coor.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_code_2fProto_2fcoor_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_code_2fProto_2fcoor_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_code_2fProto_2fcoor_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_code_2fProto_2fcoor_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_code_2fProto_2fcoor_2eproto;
namespace coor {
class RaftAppendEntries;
struct RaftAppendEntriesDefaultTypeInternal;
extern RaftAppendEntriesDefaultTypeInternal _RaftAppendEntries_default_instance_;
class RaftAppendEntriesRsp;
struct RaftAppendEntriesRspDefaultTypeInternal;
extern RaftAppendEntriesRspDefaultTypeInternal _RaftAppendEntriesRsp_default_instance_;
class RaftOnlineNodeEntry;
struct RaftOnlineNodeEntryDefaultTypeInternal;
extern RaftOnlineNodeEntryDefaultTypeInternal _RaftOnlineNodeEntry_default_instance_;
class RaftRequestVote;
struct RaftRequestVoteDefaultTypeInternal;
extern RaftRequestVoteDefaultTypeInternal _RaftRequestVote_default_instance_;
class RaftRequestVoteRsp;
struct RaftRequestVoteRspDefaultTypeInternal;
extern RaftRequestVoteRspDefaultTypeInternal _RaftRequestVoteRsp_default_instance_;
}  // namespace coor
PROTOBUF_NAMESPACE_OPEN
template<> ::coor::RaftAppendEntries* Arena::CreateMaybeMessage<::coor::RaftAppendEntries>(Arena*);
template<> ::coor::RaftAppendEntriesRsp* Arena::CreateMaybeMessage<::coor::RaftAppendEntriesRsp>(Arena*);
template<> ::coor::RaftOnlineNodeEntry* Arena::CreateMaybeMessage<::coor::RaftOnlineNodeEntry>(Arena*);
template<> ::coor::RaftRequestVote* Arena::CreateMaybeMessage<::coor::RaftRequestVote>(Arena*);
template<> ::coor::RaftRequestVoteRsp* Arena::CreateMaybeMessage<::coor::RaftRequestVoteRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace coor {

// ===================================================================

class RaftRequestVote final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coor.RaftRequestVote) */ {
 public:
  inline RaftRequestVote() : RaftRequestVote(nullptr) {}
  ~RaftRequestVote() override;
  explicit PROTOBUF_CONSTEXPR RaftRequestVote(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftRequestVote(const RaftRequestVote& from);
  RaftRequestVote(RaftRequestVote&& from) noexcept
    : RaftRequestVote() {
    *this = ::std::move(from);
  }

  inline RaftRequestVote& operator=(const RaftRequestVote& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftRequestVote& operator=(RaftRequestVote&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftRequestVote& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftRequestVote* internal_default_instance() {
    return reinterpret_cast<const RaftRequestVote*>(
               &_RaftRequestVote_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RaftRequestVote& a, RaftRequestVote& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftRequestVote* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftRequestVote* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftRequestVote* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftRequestVote>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftRequestVote& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftRequestVote& from) {
    RaftRequestVote::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftRequestVote* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coor.RaftRequestVote";
  }
  protected:
  explicit RaftRequestVote(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCandidateIdFieldNumber = 2,
    kTermFieldNumber = 1,
    kLastLogIndexFieldNumber = 3,
    kLastLogTermFieldNumber = 4,
    kNextNodeIdAllocHintFieldNumber = 5,
  };
  // string candidate_id = 2;
  void clear_candidate_id();
  const std::string& candidate_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_candidate_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_candidate_id();
  PROTOBUF_NODISCARD std::string* release_candidate_id();
  void set_allocated_candidate_id(std::string* candidate_id);
  private:
  const std::string& _internal_candidate_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_candidate_id(const std::string& value);
  std::string* _internal_mutable_candidate_id();
  public:

  // uint64 term = 1;
  void clear_term();
  uint64_t term() const;
  void set_term(uint64_t value);
  private:
  uint64_t _internal_term() const;
  void _internal_set_term(uint64_t value);
  public:

  // uint64 last_log_index = 3;
  void clear_last_log_index();
  uint64_t last_log_index() const;
  void set_last_log_index(uint64_t value);
  private:
  uint64_t _internal_last_log_index() const;
  void _internal_set_last_log_index(uint64_t value);
  public:

  // uint64 last_log_term = 4;
  void clear_last_log_term();
  uint64_t last_log_term() const;
  void set_last_log_term(uint64_t value);
  private:
  uint64_t _internal_last_log_term() const;
  void _internal_set_last_log_term(uint64_t value);
  public:

  // uint32 next_node_id_alloc_hint = 5;
  void clear_next_node_id_alloc_hint();
  uint32_t next_node_id_alloc_hint() const;
  void set_next_node_id_alloc_hint(uint32_t value);
  private:
  uint32_t _internal_next_node_id_alloc_hint() const;
  void _internal_set_next_node_id_alloc_hint(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:coor.RaftRequestVote)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr candidate_id_;
    uint64_t term_;
    uint64_t last_log_index_;
    uint64_t last_log_term_;
    uint32_t next_node_id_alloc_hint_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_code_2fProto_2fcoor_2eproto;
};
// -------------------------------------------------------------------

class RaftRequestVoteRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coor.RaftRequestVoteRsp) */ {
 public:
  inline RaftRequestVoteRsp() : RaftRequestVoteRsp(nullptr) {}
  ~RaftRequestVoteRsp() override;
  explicit PROTOBUF_CONSTEXPR RaftRequestVoteRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftRequestVoteRsp(const RaftRequestVoteRsp& from);
  RaftRequestVoteRsp(RaftRequestVoteRsp&& from) noexcept
    : RaftRequestVoteRsp() {
    *this = ::std::move(from);
  }

  inline RaftRequestVoteRsp& operator=(const RaftRequestVoteRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftRequestVoteRsp& operator=(RaftRequestVoteRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftRequestVoteRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftRequestVoteRsp* internal_default_instance() {
    return reinterpret_cast<const RaftRequestVoteRsp*>(
               &_RaftRequestVoteRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RaftRequestVoteRsp& a, RaftRequestVoteRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftRequestVoteRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftRequestVoteRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftRequestVoteRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftRequestVoteRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftRequestVoteRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftRequestVoteRsp& from) {
    RaftRequestVoteRsp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftRequestVoteRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coor.RaftRequestVoteRsp";
  }
  protected:
  explicit RaftRequestVoteRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kVoteGrantedFieldNumber = 2,
    kVoterNextNodeIdAllocHintFieldNumber = 3,
  };
  // uint64 term = 1;
  void clear_term();
  uint64_t term() const;
  void set_term(uint64_t value);
  private:
  uint64_t _internal_term() const;
  void _internal_set_term(uint64_t value);
  public:

  // bool vote_granted = 2;
  void clear_vote_granted();
  bool vote_granted() const;
  void set_vote_granted(bool value);
  private:
  bool _internal_vote_granted() const;
  void _internal_set_vote_granted(bool value);
  public:

  // uint32 voter_next_node_id_alloc_hint = 3;
  void clear_voter_next_node_id_alloc_hint();
  uint32_t voter_next_node_id_alloc_hint() const;
  void set_voter_next_node_id_alloc_hint(uint32_t value);
  private:
  uint32_t _internal_voter_next_node_id_alloc_hint() const;
  void _internal_set_voter_next_node_id_alloc_hint(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:coor.RaftRequestVoteRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t term_;
    bool vote_granted_;
    uint32_t voter_next_node_id_alloc_hint_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_code_2fProto_2fcoor_2eproto;
};
// -------------------------------------------------------------------

class RaftOnlineNodeEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coor.RaftOnlineNodeEntry) */ {
 public:
  inline RaftOnlineNodeEntry() : RaftOnlineNodeEntry(nullptr) {}
  ~RaftOnlineNodeEntry() override;
  explicit PROTOBUF_CONSTEXPR RaftOnlineNodeEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftOnlineNodeEntry(const RaftOnlineNodeEntry& from);
  RaftOnlineNodeEntry(RaftOnlineNodeEntry&& from) noexcept
    : RaftOnlineNodeEntry() {
    *this = ::std::move(from);
  }

  inline RaftOnlineNodeEntry& operator=(const RaftOnlineNodeEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftOnlineNodeEntry& operator=(RaftOnlineNodeEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftOnlineNodeEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftOnlineNodeEntry* internal_default_instance() {
    return reinterpret_cast<const RaftOnlineNodeEntry*>(
               &_RaftOnlineNodeEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RaftOnlineNodeEntry& a, RaftOnlineNodeEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftOnlineNodeEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftOnlineNodeEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftOnlineNodeEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftOnlineNodeEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftOnlineNodeEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftOnlineNodeEntry& from) {
    RaftOnlineNodeEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftOnlineNodeEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coor.RaftOnlineNodeEntry";
  }
  protected:
  explicit RaftOnlineNodeEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeTypeFieldNumber = 1,
    kNodeIpFieldNumber = 3,
    kAccessIpFieldNumber = 5,
    kNodeIdFieldNumber = 2,
    kNodePortFieldNumber = 4,
    kAccessPortFieldNumber = 6,
    kWorkerNumFieldNumber = 7,
    kActiveTimeFieldNumber = 8,
  };
  // string node_type = 1;
  void clear_node_type();
  const std::string& node_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_type();
  PROTOBUF_NODISCARD std::string* release_node_type();
  void set_allocated_node_type(std::string* node_type);
  private:
  const std::string& _internal_node_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_type(const std::string& value);
  std::string* _internal_mutable_node_type();
  public:

  // string node_ip = 3;
  void clear_node_ip();
  const std::string& node_ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_ip();
  PROTOBUF_NODISCARD std::string* release_node_ip();
  void set_allocated_node_ip(std::string* node_ip);
  private:
  const std::string& _internal_node_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_ip(const std::string& value);
  std::string* _internal_mutable_node_ip();
  public:

  // string access_ip = 5;
  void clear_access_ip();
  const std::string& access_ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_access_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_access_ip();
  PROTOBUF_NODISCARD std::string* release_access_ip();
  void set_allocated_access_ip(std::string* access_ip);
  private:
  const std::string& _internal_access_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_access_ip(const std::string& value);
  std::string* _internal_mutable_access_ip();
  public:

  // uint32 node_id = 2;
  void clear_node_id();
  uint32_t node_id() const;
  void set_node_id(uint32_t value);
  private:
  uint32_t _internal_node_id() const;
  void _internal_set_node_id(uint32_t value);
  public:

  // uint32 node_port = 4;
  void clear_node_port();
  uint32_t node_port() const;
  void set_node_port(uint32_t value);
  private:
  uint32_t _internal_node_port() const;
  void _internal_set_node_port(uint32_t value);
  public:

  // uint32 access_port = 6;
  void clear_access_port();
  uint32_t access_port() const;
  void set_access_port(uint32_t value);
  private:
  uint32_t _internal_access_port() const;
  void _internal_set_access_port(uint32_t value);
  public:

  // uint32 worker_num = 7;
  void clear_worker_num();
  uint32_t worker_num() const;
  void set_worker_num(uint32_t value);
  private:
  uint32_t _internal_worker_num() const;
  void _internal_set_worker_num(uint32_t value);
  public:

  // double active_time = 8;
  void clear_active_time();
  double active_time() const;
  void set_active_time(double value);
  private:
  double _internal_active_time() const;
  void _internal_set_active_time(double value);
  public:

  // @@protoc_insertion_point(class_scope:coor.RaftOnlineNodeEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_ip_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr access_ip_;
    uint32_t node_id_;
    uint32_t node_port_;
    uint32_t access_port_;
    uint32_t worker_num_;
    double active_time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_code_2fProto_2fcoor_2eproto;
};
// -------------------------------------------------------------------

class RaftAppendEntries final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coor.RaftAppendEntries) */ {
 public:
  inline RaftAppendEntries() : RaftAppendEntries(nullptr) {}
  ~RaftAppendEntries() override;
  explicit PROTOBUF_CONSTEXPR RaftAppendEntries(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftAppendEntries(const RaftAppendEntries& from);
  RaftAppendEntries(RaftAppendEntries&& from) noexcept
    : RaftAppendEntries() {
    *this = ::std::move(from);
  }

  inline RaftAppendEntries& operator=(const RaftAppendEntries& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftAppendEntries& operator=(RaftAppendEntries&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftAppendEntries& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftAppendEntries* internal_default_instance() {
    return reinterpret_cast<const RaftAppendEntries*>(
               &_RaftAppendEntries_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RaftAppendEntries& a, RaftAppendEntries& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftAppendEntries* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftAppendEntries* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftAppendEntries* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftAppendEntries>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftAppendEntries& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftAppendEntries& from) {
    RaftAppendEntries::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftAppendEntries* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coor.RaftAppendEntries";
  }
  protected:
  explicit RaftAppendEntries(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOnlineNodesFieldNumber = 8,
    kLeaderIdFieldNumber = 2,
    kTermFieldNumber = 1,
    kPrevLogIndexFieldNumber = 3,
    kPrevLogTermFieldNumber = 4,
    kLeaderCommitFieldNumber = 5,
    kOnlineNodesSeqFieldNumber = 7,
    kLeaderNextNodeIdAllocFieldNumber = 6,
  };
  // repeated .coor.RaftOnlineNodeEntry online_nodes = 8;
  int online_nodes_size() const;
  private:
  int _internal_online_nodes_size() const;
  public:
  void clear_online_nodes();
  ::coor::RaftOnlineNodeEntry* mutable_online_nodes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coor::RaftOnlineNodeEntry >*
      mutable_online_nodes();
  private:
  const ::coor::RaftOnlineNodeEntry& _internal_online_nodes(int index) const;
  ::coor::RaftOnlineNodeEntry* _internal_add_online_nodes();
  public:
  const ::coor::RaftOnlineNodeEntry& online_nodes(int index) const;
  ::coor::RaftOnlineNodeEntry* add_online_nodes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coor::RaftOnlineNodeEntry >&
      online_nodes() const;

  // string leader_id = 2;
  void clear_leader_id();
  const std::string& leader_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_leader_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_leader_id();
  PROTOBUF_NODISCARD std::string* release_leader_id();
  void set_allocated_leader_id(std::string* leader_id);
  private:
  const std::string& _internal_leader_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_leader_id(const std::string& value);
  std::string* _internal_mutable_leader_id();
  public:

  // uint64 term = 1;
  void clear_term();
  uint64_t term() const;
  void set_term(uint64_t value);
  private:
  uint64_t _internal_term() const;
  void _internal_set_term(uint64_t value);
  public:

  // uint64 prev_log_index = 3;
  void clear_prev_log_index();
  uint64_t prev_log_index() const;
  void set_prev_log_index(uint64_t value);
  private:
  uint64_t _internal_prev_log_index() const;
  void _internal_set_prev_log_index(uint64_t value);
  public:

  // uint64 prev_log_term = 4;
  void clear_prev_log_term();
  uint64_t prev_log_term() const;
  void set_prev_log_term(uint64_t value);
  private:
  uint64_t _internal_prev_log_term() const;
  void _internal_set_prev_log_term(uint64_t value);
  public:

  // uint64 leader_commit = 5;
  void clear_leader_commit();
  uint64_t leader_commit() const;
  void set_leader_commit(uint64_t value);
  private:
  uint64_t _internal_leader_commit() const;
  void _internal_set_leader_commit(uint64_t value);
  public:

  // uint64 online_nodes_seq = 7;
  void clear_online_nodes_seq();
  uint64_t online_nodes_seq() const;
  void set_online_nodes_seq(uint64_t value);
  private:
  uint64_t _internal_online_nodes_seq() const;
  void _internal_set_online_nodes_seq(uint64_t value);
  public:

  // uint32 leader_next_node_id_alloc = 6;
  void clear_leader_next_node_id_alloc();
  uint32_t leader_next_node_id_alloc() const;
  void set_leader_next_node_id_alloc(uint32_t value);
  private:
  uint32_t _internal_leader_next_node_id_alloc() const;
  void _internal_set_leader_next_node_id_alloc(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:coor.RaftAppendEntries)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coor::RaftOnlineNodeEntry > online_nodes_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr leader_id_;
    uint64_t term_;
    uint64_t prev_log_index_;
    uint64_t prev_log_term_;
    uint64_t leader_commit_;
    uint64_t online_nodes_seq_;
    uint32_t leader_next_node_id_alloc_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_code_2fProto_2fcoor_2eproto;
};
// -------------------------------------------------------------------

class RaftAppendEntriesRsp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coor.RaftAppendEntriesRsp) */ {
 public:
  inline RaftAppendEntriesRsp() : RaftAppendEntriesRsp(nullptr) {}
  ~RaftAppendEntriesRsp() override;
  explicit PROTOBUF_CONSTEXPR RaftAppendEntriesRsp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RaftAppendEntriesRsp(const RaftAppendEntriesRsp& from);
  RaftAppendEntriesRsp(RaftAppendEntriesRsp&& from) noexcept
    : RaftAppendEntriesRsp() {
    *this = ::std::move(from);
  }

  inline RaftAppendEntriesRsp& operator=(const RaftAppendEntriesRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftAppendEntriesRsp& operator=(RaftAppendEntriesRsp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RaftAppendEntriesRsp& default_instance() {
    return *internal_default_instance();
  }
  static inline const RaftAppendEntriesRsp* internal_default_instance() {
    return reinterpret_cast<const RaftAppendEntriesRsp*>(
               &_RaftAppendEntriesRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RaftAppendEntriesRsp& a, RaftAppendEntriesRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(RaftAppendEntriesRsp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftAppendEntriesRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RaftAppendEntriesRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RaftAppendEntriesRsp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RaftAppendEntriesRsp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RaftAppendEntriesRsp& from) {
    RaftAppendEntriesRsp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RaftAppendEntriesRsp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coor.RaftAppendEntriesRsp";
  }
  protected:
  explicit RaftAppendEntriesRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTermFieldNumber = 1,
    kSuccessFieldNumber = 2,
  };
  // uint64 term = 1;
  void clear_term();
  uint64_t term() const;
  void set_term(uint64_t value);
  private:
  uint64_t _internal_term() const;
  void _internal_set_term(uint64_t value);
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:coor.RaftAppendEntriesRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t term_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_code_2fProto_2fcoor_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RaftRequestVote

// uint64 term = 1;
inline void RaftRequestVote::clear_term() {
  _impl_.term_ = uint64_t{0u};
}
inline uint64_t RaftRequestVote::_internal_term() const {
  return _impl_.term_;
}
inline uint64_t RaftRequestVote::term() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.term)
  return _internal_term();
}
inline void RaftRequestVote::_internal_set_term(uint64_t value) {
  
  _impl_.term_ = value;
}
inline void RaftRequestVote::set_term(uint64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.term)
}

// string candidate_id = 2;
inline void RaftRequestVote::clear_candidate_id() {
  _impl_.candidate_id_.ClearToEmpty();
}
inline const std::string& RaftRequestVote::candidate_id() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.candidate_id)
  return _internal_candidate_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftRequestVote::set_candidate_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.candidate_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.candidate_id)
}
inline std::string* RaftRequestVote::mutable_candidate_id() {
  std::string* _s = _internal_mutable_candidate_id();
  // @@protoc_insertion_point(field_mutable:coor.RaftRequestVote.candidate_id)
  return _s;
}
inline const std::string& RaftRequestVote::_internal_candidate_id() const {
  return _impl_.candidate_id_.Get();
}
inline void RaftRequestVote::_internal_set_candidate_id(const std::string& value) {
  
  _impl_.candidate_id_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftRequestVote::_internal_mutable_candidate_id() {
  
  return _impl_.candidate_id_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftRequestVote::release_candidate_id() {
  // @@protoc_insertion_point(field_release:coor.RaftRequestVote.candidate_id)
  return _impl_.candidate_id_.Release();
}
inline void RaftRequestVote::set_allocated_candidate_id(std::string* candidate_id) {
  if (candidate_id != nullptr) {
    
  } else {
    
  }
  _impl_.candidate_id_.SetAllocated(candidate_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.candidate_id_.IsDefault()) {
    _impl_.candidate_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coor.RaftRequestVote.candidate_id)
}

// uint64 last_log_index = 3;
inline void RaftRequestVote::clear_last_log_index() {
  _impl_.last_log_index_ = uint64_t{0u};
}
inline uint64_t RaftRequestVote::_internal_last_log_index() const {
  return _impl_.last_log_index_;
}
inline uint64_t RaftRequestVote::last_log_index() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.last_log_index)
  return _internal_last_log_index();
}
inline void RaftRequestVote::_internal_set_last_log_index(uint64_t value) {
  
  _impl_.last_log_index_ = value;
}
inline void RaftRequestVote::set_last_log_index(uint64_t value) {
  _internal_set_last_log_index(value);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.last_log_index)
}

// uint64 last_log_term = 4;
inline void RaftRequestVote::clear_last_log_term() {
  _impl_.last_log_term_ = uint64_t{0u};
}
inline uint64_t RaftRequestVote::_internal_last_log_term() const {
  return _impl_.last_log_term_;
}
inline uint64_t RaftRequestVote::last_log_term() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.last_log_term)
  return _internal_last_log_term();
}
inline void RaftRequestVote::_internal_set_last_log_term(uint64_t value) {
  
  _impl_.last_log_term_ = value;
}
inline void RaftRequestVote::set_last_log_term(uint64_t value) {
  _internal_set_last_log_term(value);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.last_log_term)
}

// uint32 next_node_id_alloc_hint = 5;
inline void RaftRequestVote::clear_next_node_id_alloc_hint() {
  _impl_.next_node_id_alloc_hint_ = 0u;
}
inline uint32_t RaftRequestVote::_internal_next_node_id_alloc_hint() const {
  return _impl_.next_node_id_alloc_hint_;
}
inline uint32_t RaftRequestVote::next_node_id_alloc_hint() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.next_node_id_alloc_hint)
  return _internal_next_node_id_alloc_hint();
}
inline void RaftRequestVote::_internal_set_next_node_id_alloc_hint(uint32_t value) {
  
  _impl_.next_node_id_alloc_hint_ = value;
}
inline void RaftRequestVote::set_next_node_id_alloc_hint(uint32_t value) {
  _internal_set_next_node_id_alloc_hint(value);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.next_node_id_alloc_hint)
}

// -------------------------------------------------------------------

// RaftRequestVoteRsp

// uint64 term = 1;
inline void RaftRequestVoteRsp::clear_term() {
  _impl_.term_ = uint64_t{0u};
}
inline uint64_t RaftRequestVoteRsp::_internal_term() const {
  return _impl_.term_;
}
inline uint64_t RaftRequestVoteRsp::term() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVoteRsp.term)
  return _internal_term();
}
inline void RaftRequestVoteRsp::_internal_set_term(uint64_t value) {
  
  _impl_.term_ = value;
}
inline void RaftRequestVoteRsp::set_term(uint64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVoteRsp.term)
}

// bool vote_granted = 2;
inline void RaftRequestVoteRsp::clear_vote_granted() {
  _impl_.vote_granted_ = false;
}
inline bool RaftRequestVoteRsp::_internal_vote_granted() const {
  return _impl_.vote_granted_;
}
inline bool RaftRequestVoteRsp::vote_granted() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVoteRsp.vote_granted)
  return _internal_vote_granted();
}
inline void RaftRequestVoteRsp::_internal_set_vote_granted(bool value) {
  
  _impl_.vote_granted_ = value;
}
inline void RaftRequestVoteRsp::set_vote_granted(bool value) {
  _internal_set_vote_granted(value);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVoteRsp.vote_granted)
}

// uint32 voter_next_node_id_alloc_hint = 3;
inline void RaftRequestVoteRsp::clear_voter_next_node_id_alloc_hint() {
  _impl_.voter_next_node_id_alloc_hint_ = 0u;
}
inline uint32_t RaftRequestVoteRsp::_internal_voter_next_node_id_alloc_hint() const {
  return _impl_.voter_next_node_id_alloc_hint_;
}
inline uint32_t RaftRequestVoteRsp::voter_next_node_id_alloc_hint() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVoteRsp.voter_next_node_id_alloc_hint)
  return _internal_voter_next_node_id_alloc_hint();
}
inline void RaftRequestVoteRsp::_internal_set_voter_next_node_id_alloc_hint(uint32_t value) {
  
  _impl_.voter_next_node_id_alloc_hint_ = value;
}
inline void RaftRequestVoteRsp::set_voter_next_node_id_alloc_hint(uint32_t value) {
  _internal_set_voter_next_node_id_alloc_hint(value);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVoteRsp.voter_next_node_id_alloc_hint)
}

// -------------------------------------------------------------------

// RaftOnlineNodeEntry

// string node_type = 1;
inline void RaftOnlineNodeEntry::clear_node_type() {
  _impl_.node_type_.ClearToEmpty();
}
inline const std::string& RaftOnlineNodeEntry::node_type() const {
  // @@protoc_insertion_point(field_get:coor.RaftOnlineNodeEntry.node_type)
  return _internal_node_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftOnlineNodeEntry::set_node_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.node_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coor.RaftOnlineNodeEntry.node_type)
}
inline std::string* RaftOnlineNodeEntry::mutable_node_type() {
  std::string* _s = _internal_mutable_node_type();
  // @@protoc_insertion_point(field_mutable:coor.RaftOnlineNodeEntry.node_type)
  return _s;
}
inline const std::string& RaftOnlineNodeEntry::_internal_node_type() const {
  return _impl_.node_type_.Get();
}
inline void RaftOnlineNodeEntry::_internal_set_node_type(const std::string& value) {
  
  _impl_.node_type_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftOnlineNodeEntry::_internal_mutable_node_type() {
  
  return _impl_.node_type_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftOnlineNodeEntry::release_node_type() {
  // @@protoc_insertion_point(field_release:coor.RaftOnlineNodeEntry.node_type)
  return _impl_.node_type_.Release();
}
inline void RaftOnlineNodeEntry::set_allocated_node_type(std::string* node_type) {
  if (node_type != nullptr) {
    
  } else {
    
  }
  _impl_.node_type_.SetAllocated(node_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.node_type_.IsDefault()) {
    _impl_.node_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coor.RaftOnlineNodeEntry.node_type)
}

// uint32 node_id = 2;
inline void RaftOnlineNodeEntry::clear_node_id() {
  _impl_.node_id_ = 0u;
}
inline uint32_t RaftOnlineNodeEntry::_internal_node_id() const {
  return _impl_.node_id_;
}
inline uint32_t RaftOnlineNodeEntry::node_id() const {
  // @@protoc_insertion_point(field_get:coor.RaftOnlineNodeEntry.node_id)
  return _internal_node_id();
}
inline void RaftOnlineNodeEntry::_internal_set_node_id(uint32_t value) {
  
  _impl_.node_id_ = value;
}
inline void RaftOnlineNodeEntry::set_node_id(uint32_t value) {
  _internal_set_node_id(value);
  // @@protoc_insertion_point(field_set:coor.RaftOnlineNodeEntry.node_id)
}

// string node_ip = 3;
inline void RaftOnlineNodeEntry::clear_node_ip() {
  _impl_.node_ip_.ClearToEmpty();
}
inline const std::string& RaftOnlineNodeEntry::node_ip() const {
  // @@protoc_insertion_point(field_get:coor.RaftOnlineNodeEntry.node_ip)
  return _internal_node_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftOnlineNodeEntry::set_node_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.node_ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coor.RaftOnlineNodeEntry.node_ip)
}
inline std::string* RaftOnlineNodeEntry::mutable_node_ip() {
  std::string* _s = _internal_mutable_node_ip();
  // @@protoc_insertion_point(field_mutable:coor.RaftOnlineNodeEntry.node_ip)
  return _s;
}
inline const std::string& RaftOnlineNodeEntry::_internal_node_ip() const {
  return _impl_.node_ip_.Get();
}
inline void RaftOnlineNodeEntry::_internal_set_node_ip(const std::string& value) {
  
  _impl_.node_ip_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftOnlineNodeEntry::_internal_mutable_node_ip() {
  
  return _impl_.node_ip_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftOnlineNodeEntry::release_node_ip() {
  // @@protoc_insertion_point(field_release:coor.RaftOnlineNodeEntry.node_ip)
  return _impl_.node_ip_.Release();
}
inline void RaftOnlineNodeEntry::set_allocated_node_ip(std::string* node_ip) {
  if (node_ip != nullptr) {
    
  } else {
    
  }
  _impl_.node_ip_.SetAllocated(node_ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.node_ip_.IsDefault()) {
    _impl_.node_ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coor.RaftOnlineNodeEntry.node_ip)
}

// uint32 node_port = 4;
inline void RaftOnlineNodeEntry::clear_node_port() {
  _impl_.node_port_ = 0u;
}
inline uint32_t RaftOnlineNodeEntry::_internal_node_port() const {
  return _impl_.node_port_;
}
inline uint32_t RaftOnlineNodeEntry::node_port() const {
  // @@protoc_insertion_point(field_get:coor.RaftOnlineNodeEntry.node_port)
  return _internal_node_port();
}
inline void RaftOnlineNodeEntry::_internal_set_node_port(uint32_t value) {
  
  _impl_.node_port_ = value;
}
inline void RaftOnlineNodeEntry::set_node_port(uint32_t value) {
  _internal_set_node_port(value);
  // @@protoc_insertion_point(field_set:coor.RaftOnlineNodeEntry.node_port)
}

// string access_ip = 5;
inline void RaftOnlineNodeEntry::clear_access_ip() {
  _impl_.access_ip_.ClearToEmpty();
}
inline const std::string& RaftOnlineNodeEntry::access_ip() const {
  // @@protoc_insertion_point(field_get:coor.RaftOnlineNodeEntry.access_ip)
  return _internal_access_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftOnlineNodeEntry::set_access_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.access_ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coor.RaftOnlineNodeEntry.access_ip)
}
inline std::string* RaftOnlineNodeEntry::mutable_access_ip() {
  std::string* _s = _internal_mutable_access_ip();
  // @@protoc_insertion_point(field_mutable:coor.RaftOnlineNodeEntry.access_ip)
  return _s;
}
inline const std::string& RaftOnlineNodeEntry::_internal_access_ip() const {
  return _impl_.access_ip_.Get();
}
inline void RaftOnlineNodeEntry::_internal_set_access_ip(const std::string& value) {
  
  _impl_.access_ip_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftOnlineNodeEntry::_internal_mutable_access_ip() {
  
  return _impl_.access_ip_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftOnlineNodeEntry::release_access_ip() {
  // @@protoc_insertion_point(field_release:coor.RaftOnlineNodeEntry.access_ip)
  return _impl_.access_ip_.Release();
}
inline void RaftOnlineNodeEntry::set_allocated_access_ip(std::string* access_ip) {
  if (access_ip != nullptr) {
    
  } else {
    
  }
  _impl_.access_ip_.SetAllocated(access_ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.access_ip_.IsDefault()) {
    _impl_.access_ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coor.RaftOnlineNodeEntry.access_ip)
}

// uint32 access_port = 6;
inline void RaftOnlineNodeEntry::clear_access_port() {
  _impl_.access_port_ = 0u;
}
inline uint32_t RaftOnlineNodeEntry::_internal_access_port() const {
  return _impl_.access_port_;
}
inline uint32_t RaftOnlineNodeEntry::access_port() const {
  // @@protoc_insertion_point(field_get:coor.RaftOnlineNodeEntry.access_port)
  return _internal_access_port();
}
inline void RaftOnlineNodeEntry::_internal_set_access_port(uint32_t value) {
  
  _impl_.access_port_ = value;
}
inline void RaftOnlineNodeEntry::set_access_port(uint32_t value) {
  _internal_set_access_port(value);
  // @@protoc_insertion_point(field_set:coor.RaftOnlineNodeEntry.access_port)
}

// uint32 worker_num = 7;
inline void RaftOnlineNodeEntry::clear_worker_num() {
  _impl_.worker_num_ = 0u;
}
inline uint32_t RaftOnlineNodeEntry::_internal_worker_num() const {
  return _impl_.worker_num_;
}
inline uint32_t RaftOnlineNodeEntry::worker_num() const {
  // @@protoc_insertion_point(field_get:coor.RaftOnlineNodeEntry.worker_num)
  return _internal_worker_num();
}
inline void RaftOnlineNodeEntry::_internal_set_worker_num(uint32_t value) {
  
  _impl_.worker_num_ = value;
}
inline void RaftOnlineNodeEntry::set_worker_num(uint32_t value) {
  _internal_set_worker_num(value);
  // @@protoc_insertion_point(field_set:coor.RaftOnlineNodeEntry.worker_num)
}

// double active_time = 8;
inline void RaftOnlineNodeEntry::clear_active_time() {
  _impl_.active_time_ = 0;
}
inline double RaftOnlineNodeEntry::_internal_active_time() const {
  return _impl_.active_time_;
}
inline double RaftOnlineNodeEntry::active_time() const {
  // @@protoc_insertion_point(field_get:coor.RaftOnlineNodeEntry.active_time)
  return _internal_active_time();
}
inline void RaftOnlineNodeEntry::_internal_set_active_time(double value) {
  
  _impl_.active_time_ = value;
}
inline void RaftOnlineNodeEntry::set_active_time(double value) {
  _internal_set_active_time(value);
  // @@protoc_insertion_point(field_set:coor.RaftOnlineNodeEntry.active_time)
}

// -------------------------------------------------------------------

// RaftAppendEntries

// uint64 term = 1;
inline void RaftAppendEntries::clear_term() {
  _impl_.term_ = uint64_t{0u};
}
inline uint64_t RaftAppendEntries::_internal_term() const {
  return _impl_.term_;
}
inline uint64_t RaftAppendEntries::term() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.term)
  return _internal_term();
}
inline void RaftAppendEntries::_internal_set_term(uint64_t value) {
  
  _impl_.term_ = value;
}
inline void RaftAppendEntries::set_term(uint64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.term)
}

// string leader_id = 2;
inline void RaftAppendEntries::clear_leader_id() {
  _impl_.leader_id_.ClearToEmpty();
}
inline const std::string& RaftAppendEntries::leader_id() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.leader_id)
  return _internal_leader_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RaftAppendEntries::set_leader_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.leader_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.leader_id)
}
inline std::string* RaftAppendEntries::mutable_leader_id() {
  std::string* _s = _internal_mutable_leader_id();
  // @@protoc_insertion_point(field_mutable:coor.RaftAppendEntries.leader_id)
  return _s;
}
inline const std::string& RaftAppendEntries::_internal_leader_id() const {
  return _impl_.leader_id_.Get();
}
inline void RaftAppendEntries::_internal_set_leader_id(const std::string& value) {
  
  _impl_.leader_id_.Set(value, GetArenaForAllocation());
}
inline std::string* RaftAppendEntries::_internal_mutable_leader_id() {
  
  return _impl_.leader_id_.Mutable(GetArenaForAllocation());
}
inline std::string* RaftAppendEntries::release_leader_id() {
  // @@protoc_insertion_point(field_release:coor.RaftAppendEntries.leader_id)
  return _impl_.leader_id_.Release();
}
inline void RaftAppendEntries::set_allocated_leader_id(std::string* leader_id) {
  if (leader_id != nullptr) {
    
  } else {
    
  }
  _impl_.leader_id_.SetAllocated(leader_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.leader_id_.IsDefault()) {
    _impl_.leader_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coor.RaftAppendEntries.leader_id)
}

// uint64 prev_log_index = 3;
inline void RaftAppendEntries::clear_prev_log_index() {
  _impl_.prev_log_index_ = uint64_t{0u};
}
inline uint64_t RaftAppendEntries::_internal_prev_log_index() const {
  return _impl_.prev_log_index_;
}
inline uint64_t RaftAppendEntries::prev_log_index() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.prev_log_index)
  return _internal_prev_log_index();
}
inline void RaftAppendEntries::_internal_set_prev_log_index(uint64_t value) {
  
  _impl_.prev_log_index_ = value;
}
inline void RaftAppendEntries::set_prev_log_index(uint64_t value) {
  _internal_set_prev_log_index(value);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.prev_log_index)
}

// uint64 prev_log_term = 4;
inline void RaftAppendEntries::clear_prev_log_term() {
  _impl_.prev_log_term_ = uint64_t{0u};
}
inline uint64_t RaftAppendEntries::_internal_prev_log_term() const {
  return _impl_.prev_log_term_;
}
inline uint64_t RaftAppendEntries::prev_log_term() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.prev_log_term)
  return _internal_prev_log_term();
}
inline void RaftAppendEntries::_internal_set_prev_log_term(uint64_t value) {
  
  _impl_.prev_log_term_ = value;
}
inline void RaftAppendEntries::set_prev_log_term(uint64_t value) {
  _internal_set_prev_log_term(value);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.prev_log_term)
}

// uint64 leader_commit = 5;
inline void RaftAppendEntries::clear_leader_commit() {
  _impl_.leader_commit_ = uint64_t{0u};
}
inline uint64_t RaftAppendEntries::_internal_leader_commit() const {
  return _impl_.leader_commit_;
}
inline uint64_t RaftAppendEntries::leader_commit() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.leader_commit)
  return _internal_leader_commit();
}
inline void RaftAppendEntries::_internal_set_leader_commit(uint64_t value) {
  
  _impl_.leader_commit_ = value;
}
inline void RaftAppendEntries::set_leader_commit(uint64_t value) {
  _internal_set_leader_commit(value);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.leader_commit)
}

// uint32 leader_next_node_id_alloc = 6;
inline void RaftAppendEntries::clear_leader_next_node_id_alloc() {
  _impl_.leader_next_node_id_alloc_ = 0u;
}
inline uint32_t RaftAppendEntries::_internal_leader_next_node_id_alloc() const {
  return _impl_.leader_next_node_id_alloc_;
}
inline uint32_t RaftAppendEntries::leader_next_node_id_alloc() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.leader_next_node_id_alloc)
  return _internal_leader_next_node_id_alloc();
}
inline void RaftAppendEntries::_internal_set_leader_next_node_id_alloc(uint32_t value) {
  
  _impl_.leader_next_node_id_alloc_ = value;
}
inline void RaftAppendEntries::set_leader_next_node_id_alloc(uint32_t value) {
  _internal_set_leader_next_node_id_alloc(value);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.leader_next_node_id_alloc)
}

// uint64 online_nodes_seq = 7;
inline void RaftAppendEntries::clear_online_nodes_seq() {
  _impl_.online_nodes_seq_ = uint64_t{0u};
}
inline uint64_t RaftAppendEntries::_internal_online_nodes_seq() const {
  return _impl_.online_nodes_seq_;
}
inline uint64_t RaftAppendEntries::online_nodes_seq() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.online_nodes_seq)
  return _internal_online_nodes_seq();
}
inline void RaftAppendEntries::_internal_set_online_nodes_seq(uint64_t value) {
  
  _impl_.online_nodes_seq_ = value;
}
inline void RaftAppendEntries::set_online_nodes_seq(uint64_t value) {
  _internal_set_online_nodes_seq(value);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.online_nodes_seq)
}

// repeated .coor.RaftOnlineNodeEntry online_nodes = 8;
inline int RaftAppendEntries::_internal_online_nodes_size() const {
  return _impl_.online_nodes_.size();
}
inline int RaftAppendEntries::online_nodes_size() const {
  return _internal_online_nodes_size();
}
inline void RaftAppendEntries::clear_online_nodes() {
  _impl_.online_nodes_.Clear();
}
inline ::coor::RaftOnlineNodeEntry* RaftAppendEntries::mutable_online_nodes(int index) {
  // @@protoc_insertion_point(field_mutable:coor.RaftAppendEntries.online_nodes)
  return _impl_.online_nodes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coor::RaftOnlineNodeEntry >*
RaftAppendEntries::mutable_online_nodes() {
  // @@protoc_insertion_point(field_mutable_list:coor.RaftAppendEntries.online_nodes)
  return &_impl_.online_nodes_;
}
inline const ::coor::RaftOnlineNodeEntry& RaftAppendEntries::_internal_online_nodes(int index) const {
  return _impl_.online_nodes_.Get(index);
}
inline const ::coor::RaftOnlineNodeEntry& RaftAppendEntries::online_nodes(int index) const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.online_nodes)
  return _internal_online_nodes(index);
}
inline ::coor::RaftOnlineNodeEntry* RaftAppendEntries::_internal_add_online_nodes() {
  return _impl_.online_nodes_.Add();
}
inline ::coor::RaftOnlineNodeEntry* RaftAppendEntries::add_online_nodes() {
  ::coor::RaftOnlineNodeEntry* _add = _internal_add_online_nodes();
  // @@protoc_insertion_point(field_add:coor.RaftAppendEntries.online_nodes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::coor::RaftOnlineNodeEntry >&
RaftAppendEntries::online_nodes() const {
  // @@protoc_insertion_point(field_list:coor.RaftAppendEntries.online_nodes)
  return _impl_.online_nodes_;
}

// -------------------------------------------------------------------

// RaftAppendEntriesRsp

// uint64 term = 1;
inline void RaftAppendEntriesRsp::clear_term() {
  _impl_.term_ = uint64_t{0u};
}
inline uint64_t RaftAppendEntriesRsp::_internal_term() const {
  return _impl_.term_;
}
inline uint64_t RaftAppendEntriesRsp::term() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntriesRsp.term)
  return _internal_term();
}
inline void RaftAppendEntriesRsp::_internal_set_term(uint64_t value) {
  
  _impl_.term_ = value;
}
inline void RaftAppendEntriesRsp::set_term(uint64_t value) {
  _internal_set_term(value);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntriesRsp.term)
}

// bool success = 2;
inline void RaftAppendEntriesRsp::clear_success() {
  _impl_.success_ = false;
}
inline bool RaftAppendEntriesRsp::_internal_success() const {
  return _impl_.success_;
}
inline bool RaftAppendEntriesRsp::success() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntriesRsp.success)
  return _internal_success();
}
inline void RaftAppendEntriesRsp::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void RaftAppendEntriesRsp::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntriesRsp.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace coor

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_code_2fProto_2fcoor_2eproto
