// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: coor.proto
// Protobuf C++ Version: 7.34.1

#ifndef coor_2eproto_2epb_2eh
#define coor_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_coor_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_coor_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_coor_2eproto;
}  // extern "C"
namespace coor {
class RaftAppendEntries;
struct RaftAppendEntriesDefaultTypeInternal;
extern RaftAppendEntriesDefaultTypeInternal _RaftAppendEntries_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RaftAppendEntries_class_data_;
class RaftAppendEntriesRsp;
struct RaftAppendEntriesRspDefaultTypeInternal;
extern RaftAppendEntriesRspDefaultTypeInternal _RaftAppendEntriesRsp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RaftAppendEntriesRsp_class_data_;
class RaftRequestVote;
struct RaftRequestVoteDefaultTypeInternal;
extern RaftRequestVoteDefaultTypeInternal _RaftRequestVote_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RaftRequestVote_class_data_;
class RaftRequestVoteRsp;
struct RaftRequestVoteRspDefaultTypeInternal;
extern RaftRequestVoteRspDefaultTypeInternal _RaftRequestVoteRsp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RaftRequestVoteRsp_class_data_;
}  // namespace coor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace coor {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED RaftRequestVoteRsp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:coor.RaftRequestVoteRsp) */ {
 public:
  inline RaftRequestVoteRsp() : RaftRequestVoteRsp(nullptr) {}
  ~RaftRequestVoteRsp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RaftRequestVoteRsp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RaftRequestVoteRsp));
  }
#endif

  template <typename = void>
  explicit constexpr RaftRequestVoteRsp(::google::protobuf::internal::ConstantInitialized);

  inline RaftRequestVoteRsp(const RaftRequestVoteRsp& from) : RaftRequestVoteRsp(nullptr, from) {}
  inline RaftRequestVoteRsp(RaftRequestVoteRsp&& from) noexcept
      : RaftRequestVoteRsp(nullptr, ::std::move(from)) {}
  inline RaftRequestVoteRsp& operator=(const RaftRequestVoteRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftRequestVoteRsp& operator=(RaftRequestVoteRsp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const RaftRequestVoteRsp& default_instance() {
    return *reinterpret_cast<const RaftRequestVoteRsp*>(
        &_RaftRequestVoteRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RaftRequestVoteRsp& a, RaftRequestVoteRsp& b) { a.Swap(&b); }
  inline void Swap(RaftRequestVoteRsp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftRequestVoteRsp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] RaftRequestVoteRsp* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RaftRequestVoteRsp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RaftRequestVoteRsp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RaftRequestVoteRsp& from) { RaftRequestVoteRsp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RaftRequestVoteRsp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "coor.RaftRequestVoteRsp"; }

  explicit RaftRequestVoteRsp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RaftRequestVoteRsp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RaftRequestVoteRsp& from);
  RaftRequestVoteRsp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RaftRequestVoteRsp&& from) noexcept
      : RaftRequestVoteRsp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermFieldNumber = 1,
    kVoteGrantedFieldNumber = 2,
    kVoterNextNodeIdAllocHintFieldNumber = 3,
  };
  // uint64 term = 1;
  void clear_term() ;
  [[nodiscard]] ::uint64_t term() const;
  void set_term(::uint64_t value);

  private:
  ::uint64_t _internal_term() const;
  void _internal_set_term(::uint64_t value);

  public:
  // bool vote_granted = 2;
  void clear_vote_granted() ;
  [[nodiscard]] bool vote_granted() const;
  void set_vote_granted(bool value);

  private:
  bool _internal_vote_granted() const;
  void _internal_set_vote_granted(bool value);

  public:
  // uint32 voter_next_node_id_alloc_hint = 3;
  void clear_voter_next_node_id_alloc_hint() ;
  [[nodiscard]] ::uint32_t voter_next_node_id_alloc_hint() const;
  void set_voter_next_node_id_alloc_hint(::uint32_t value);

  private:
  ::uint32_t _internal_voter_next_node_id_alloc_hint() const;
  void _internal_set_voter_next_node_id_alloc_hint(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:coor.RaftRequestVoteRsp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RaftRequestVoteRsp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t term_;
    bool vote_granted_;
    ::uint32_t voter_next_node_id_alloc_hint_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_coor_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RaftRequestVoteRsp_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED RaftRequestVote final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:coor.RaftRequestVote) */ {
 public:
  inline RaftRequestVote() : RaftRequestVote(nullptr) {}
  ~RaftRequestVote() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RaftRequestVote* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RaftRequestVote));
  }
#endif

  template <typename = void>
  explicit constexpr RaftRequestVote(::google::protobuf::internal::ConstantInitialized);

  inline RaftRequestVote(const RaftRequestVote& from) : RaftRequestVote(nullptr, from) {}
  inline RaftRequestVote(RaftRequestVote&& from) noexcept
      : RaftRequestVote(nullptr, ::std::move(from)) {}
  inline RaftRequestVote& operator=(const RaftRequestVote& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftRequestVote& operator=(RaftRequestVote&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const RaftRequestVote& default_instance() {
    return *reinterpret_cast<const RaftRequestVote*>(
        &_RaftRequestVote_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RaftRequestVote& a, RaftRequestVote& b) { a.Swap(&b); }
  inline void Swap(RaftRequestVote* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftRequestVote* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] RaftRequestVote* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RaftRequestVote>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RaftRequestVote& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RaftRequestVote& from) { RaftRequestVote::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RaftRequestVote* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "coor.RaftRequestVote"; }

  explicit RaftRequestVote(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RaftRequestVote(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RaftRequestVote& from);
  RaftRequestVote(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RaftRequestVote&& from) noexcept
      : RaftRequestVote(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCandidateIdFieldNumber = 2,
    kTermFieldNumber = 1,
    kLastLogIndexFieldNumber = 3,
    kLastLogTermFieldNumber = 4,
    kNextNodeIdAllocHintFieldNumber = 5,
  };
  // string candidate_id = 2;
  void clear_candidate_id() ;
  [[nodiscard]] const ::std::string& candidate_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_candidate_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_candidate_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_candidate_id();
  void set_allocated_candidate_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_candidate_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_candidate_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_candidate_id();

  public:
  // uint64 term = 1;
  void clear_term() ;
  [[nodiscard]] ::uint64_t term() const;
  void set_term(::uint64_t value);

  private:
  ::uint64_t _internal_term() const;
  void _internal_set_term(::uint64_t value);

  public:
  // uint64 last_log_index = 3;
  void clear_last_log_index() ;
  [[nodiscard]] ::uint64_t last_log_index() const;
  void set_last_log_index(::uint64_t value);

  private:
  ::uint64_t _internal_last_log_index() const;
  void _internal_set_last_log_index(::uint64_t value);

  public:
  // uint64 last_log_term = 4;
  void clear_last_log_term() ;
  [[nodiscard]] ::uint64_t last_log_term() const;
  void set_last_log_term(::uint64_t value);

  private:
  ::uint64_t _internal_last_log_term() const;
  void _internal_set_last_log_term(::uint64_t value);

  public:
  // uint32 next_node_id_alloc_hint = 5;
  void clear_next_node_id_alloc_hint() ;
  [[nodiscard]] ::uint32_t next_node_id_alloc_hint() const;
  void set_next_node_id_alloc_hint(::uint32_t value);

  private:
  ::uint32_t _internal_next_node_id_alloc_hint() const;
  void _internal_set_next_node_id_alloc_hint(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:coor.RaftRequestVote)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 41,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RaftRequestVote& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr candidate_id_;
    ::uint64_t term_;
    ::uint64_t last_log_index_;
    ::uint64_t last_log_term_;
    ::uint32_t next_node_id_alloc_hint_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_coor_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RaftRequestVote_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED RaftAppendEntriesRsp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:coor.RaftAppendEntriesRsp) */ {
 public:
  inline RaftAppendEntriesRsp() : RaftAppendEntriesRsp(nullptr) {}
  ~RaftAppendEntriesRsp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RaftAppendEntriesRsp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RaftAppendEntriesRsp));
  }
#endif

  template <typename = void>
  explicit constexpr RaftAppendEntriesRsp(::google::protobuf::internal::ConstantInitialized);

  inline RaftAppendEntriesRsp(const RaftAppendEntriesRsp& from) : RaftAppendEntriesRsp(nullptr, from) {}
  inline RaftAppendEntriesRsp(RaftAppendEntriesRsp&& from) noexcept
      : RaftAppendEntriesRsp(nullptr, ::std::move(from)) {}
  inline RaftAppendEntriesRsp& operator=(const RaftAppendEntriesRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftAppendEntriesRsp& operator=(RaftAppendEntriesRsp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const RaftAppendEntriesRsp& default_instance() {
    return *reinterpret_cast<const RaftAppendEntriesRsp*>(
        &_RaftAppendEntriesRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(RaftAppendEntriesRsp& a, RaftAppendEntriesRsp& b) { a.Swap(&b); }
  inline void Swap(RaftAppendEntriesRsp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftAppendEntriesRsp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] RaftAppendEntriesRsp* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RaftAppendEntriesRsp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RaftAppendEntriesRsp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RaftAppendEntriesRsp& from) { RaftAppendEntriesRsp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RaftAppendEntriesRsp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "coor.RaftAppendEntriesRsp"; }

  explicit RaftAppendEntriesRsp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RaftAppendEntriesRsp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RaftAppendEntriesRsp& from);
  RaftAppendEntriesRsp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RaftAppendEntriesRsp&& from) noexcept
      : RaftAppendEntriesRsp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTermFieldNumber = 1,
    kSuccessFieldNumber = 2,
  };
  // uint64 term = 1;
  void clear_term() ;
  [[nodiscard]] ::uint64_t term() const;
  void set_term(::uint64_t value);

  private:
  ::uint64_t _internal_term() const;
  void _internal_set_term(::uint64_t value);

  public:
  // bool success = 2;
  void clear_success() ;
  [[nodiscard]] bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:coor.RaftAppendEntriesRsp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RaftAppendEntriesRsp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t term_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_coor_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RaftAppendEntriesRsp_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED RaftAppendEntries final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:coor.RaftAppendEntries) */ {
 public:
  inline RaftAppendEntries() : RaftAppendEntries(nullptr) {}
  ~RaftAppendEntries() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RaftAppendEntries* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RaftAppendEntries));
  }
#endif

  template <typename = void>
  explicit constexpr RaftAppendEntries(::google::protobuf::internal::ConstantInitialized);

  inline RaftAppendEntries(const RaftAppendEntries& from) : RaftAppendEntries(nullptr, from) {}
  inline RaftAppendEntries(RaftAppendEntries&& from) noexcept
      : RaftAppendEntries(nullptr, ::std::move(from)) {}
  inline RaftAppendEntries& operator=(const RaftAppendEntries& from) {
    CopyFrom(from);
    return *this;
  }
  inline RaftAppendEntries& operator=(RaftAppendEntries&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const RaftAppendEntries& default_instance() {
    return *reinterpret_cast<const RaftAppendEntries*>(
        &_RaftAppendEntries_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(RaftAppendEntries& a, RaftAppendEntries& b) { a.Swap(&b); }
  inline void Swap(RaftAppendEntries* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RaftAppendEntries* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] RaftAppendEntries* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RaftAppendEntries>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RaftAppendEntries& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RaftAppendEntries& from) { RaftAppendEntries::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RaftAppendEntries* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "coor.RaftAppendEntries"; }

  explicit RaftAppendEntries(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RaftAppendEntries(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RaftAppendEntries& from);
  RaftAppendEntries(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RaftAppendEntries&& from) noexcept
      : RaftAppendEntries(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLeaderIdFieldNumber = 2,
    kTermFieldNumber = 1,
    kPrevLogIndexFieldNumber = 3,
    kPrevLogTermFieldNumber = 4,
    kLeaderCommitFieldNumber = 5,
    kLeaderNextNodeIdAllocFieldNumber = 6,
  };
  // string leader_id = 2;
  void clear_leader_id() ;
  [[nodiscard]] const ::std::string& leader_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_leader_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_leader_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_leader_id();
  void set_allocated_leader_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_leader_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_leader_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_leader_id();

  public:
  // uint64 term = 1;
  void clear_term() ;
  [[nodiscard]] ::uint64_t term() const;
  void set_term(::uint64_t value);

  private:
  ::uint64_t _internal_term() const;
  void _internal_set_term(::uint64_t value);

  public:
  // uint64 prev_log_index = 3;
  void clear_prev_log_index() ;
  [[nodiscard]] ::uint64_t prev_log_index() const;
  void set_prev_log_index(::uint64_t value);

  private:
  ::uint64_t _internal_prev_log_index() const;
  void _internal_set_prev_log_index(::uint64_t value);

  public:
  // uint64 prev_log_term = 4;
  void clear_prev_log_term() ;
  [[nodiscard]] ::uint64_t prev_log_term() const;
  void set_prev_log_term(::uint64_t value);

  private:
  ::uint64_t _internal_prev_log_term() const;
  void _internal_set_prev_log_term(::uint64_t value);

  public:
  // uint64 leader_commit = 5;
  void clear_leader_commit() ;
  [[nodiscard]] ::uint64_t leader_commit() const;
  void set_leader_commit(::uint64_t value);

  private:
  ::uint64_t _internal_leader_commit() const;
  void _internal_set_leader_commit(::uint64_t value);

  public:
  // uint32 leader_next_node_id_alloc = 6;
  void clear_leader_next_node_id_alloc() ;
  [[nodiscard]] ::uint32_t leader_next_node_id_alloc() const;
  void set_leader_next_node_id_alloc(::uint32_t value);

  private:
  ::uint32_t _internal_leader_next_node_id_alloc() const;
  void _internal_set_leader_next_node_id_alloc(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:coor.RaftAppendEntries)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 40,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RaftAppendEntries& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr leader_id_;
    ::uint64_t term_;
    ::uint64_t prev_log_index_;
    ::uint64_t prev_log_term_;
    ::uint64_t leader_commit_;
    ::uint32_t leader_next_node_id_alloc_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_coor_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RaftAppendEntries_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RaftRequestVote

// uint64 term = 1;
inline void RaftRequestVote::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t RaftRequestVote::term() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.term)
  return _internal_term();
}
inline void RaftRequestVote::set_term(::uint64_t value) {
  _internal_set_term(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.term)
}
inline ::uint64_t RaftRequestVote::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void RaftRequestVote::_internal_set_term(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// string candidate_id = 2;
inline void RaftRequestVote::clear_candidate_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.candidate_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RaftRequestVote::candidate_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.candidate_id)
  return _internal_candidate_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RaftRequestVote::set_candidate_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.candidate_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.candidate_id)
}
inline ::std::string* PROTOBUF_NONNULL RaftRequestVote::mutable_candidate_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_candidate_id();
  // @@protoc_insertion_point(field_mutable:coor.RaftRequestVote.candidate_id)
  return _s;
}
inline const ::std::string& RaftRequestVote::_internal_candidate_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.candidate_id_.Get();
}
inline void RaftRequestVote::_internal_set_candidate_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.candidate_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RaftRequestVote::_internal_mutable_candidate_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.candidate_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RaftRequestVote::release_candidate_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:coor.RaftRequestVote.candidate_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.candidate_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.candidate_id_.Set("", GetArena());
  }
  return released;
}
inline void RaftRequestVote::set_allocated_candidate_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.candidate_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.candidate_id_.IsDefault()) {
    _impl_.candidate_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:coor.RaftRequestVote.candidate_id)
}

// uint64 last_log_index = 3;
inline void RaftRequestVote::clear_last_log_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.last_log_index_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t RaftRequestVote::last_log_index() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.last_log_index)
  return _internal_last_log_index();
}
inline void RaftRequestVote::set_last_log_index(::uint64_t value) {
  _internal_set_last_log_index(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.last_log_index)
}
inline ::uint64_t RaftRequestVote::_internal_last_log_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.last_log_index_;
}
inline void RaftRequestVote::_internal_set_last_log_index(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.last_log_index_ = value;
}

// uint64 last_log_term = 4;
inline void RaftRequestVote::clear_last_log_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.last_log_term_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t RaftRequestVote::last_log_term() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.last_log_term)
  return _internal_last_log_term();
}
inline void RaftRequestVote::set_last_log_term(::uint64_t value) {
  _internal_set_last_log_term(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.last_log_term)
}
inline ::uint64_t RaftRequestVote::_internal_last_log_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.last_log_term_;
}
inline void RaftRequestVote::_internal_set_last_log_term(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.last_log_term_ = value;
}

// uint32 next_node_id_alloc_hint = 5;
inline void RaftRequestVote::clear_next_node_id_alloc_hint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.next_node_id_alloc_hint_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t RaftRequestVote::next_node_id_alloc_hint() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVote.next_node_id_alloc_hint)
  return _internal_next_node_id_alloc_hint();
}
inline void RaftRequestVote::set_next_node_id_alloc_hint(::uint32_t value) {
  _internal_set_next_node_id_alloc_hint(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVote.next_node_id_alloc_hint)
}
inline ::uint32_t RaftRequestVote::_internal_next_node_id_alloc_hint() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.next_node_id_alloc_hint_;
}
inline void RaftRequestVote::_internal_set_next_node_id_alloc_hint(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.next_node_id_alloc_hint_ = value;
}

// -------------------------------------------------------------------

// RaftRequestVoteRsp

// uint64 term = 1;
inline void RaftRequestVoteRsp::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t RaftRequestVoteRsp::term() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVoteRsp.term)
  return _internal_term();
}
inline void RaftRequestVoteRsp::set_term(::uint64_t value) {
  _internal_set_term(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVoteRsp.term)
}
inline ::uint64_t RaftRequestVoteRsp::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void RaftRequestVoteRsp::_internal_set_term(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// bool vote_granted = 2;
inline void RaftRequestVoteRsp::clear_vote_granted() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vote_granted_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool RaftRequestVoteRsp::vote_granted() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVoteRsp.vote_granted)
  return _internal_vote_granted();
}
inline void RaftRequestVoteRsp::set_vote_granted(bool value) {
  _internal_set_vote_granted(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVoteRsp.vote_granted)
}
inline bool RaftRequestVoteRsp::_internal_vote_granted() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vote_granted_;
}
inline void RaftRequestVoteRsp::_internal_set_vote_granted(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vote_granted_ = value;
}

// uint32 voter_next_node_id_alloc_hint = 3;
inline void RaftRequestVoteRsp::clear_voter_next_node_id_alloc_hint() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.voter_next_node_id_alloc_hint_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t RaftRequestVoteRsp::voter_next_node_id_alloc_hint() const {
  // @@protoc_insertion_point(field_get:coor.RaftRequestVoteRsp.voter_next_node_id_alloc_hint)
  return _internal_voter_next_node_id_alloc_hint();
}
inline void RaftRequestVoteRsp::set_voter_next_node_id_alloc_hint(::uint32_t value) {
  _internal_set_voter_next_node_id_alloc_hint(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:coor.RaftRequestVoteRsp.voter_next_node_id_alloc_hint)
}
inline ::uint32_t RaftRequestVoteRsp::_internal_voter_next_node_id_alloc_hint() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.voter_next_node_id_alloc_hint_;
}
inline void RaftRequestVoteRsp::_internal_set_voter_next_node_id_alloc_hint(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.voter_next_node_id_alloc_hint_ = value;
}

// -------------------------------------------------------------------

// RaftAppendEntries

// uint64 term = 1;
inline void RaftAppendEntries::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t RaftAppendEntries::term() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.term)
  return _internal_term();
}
inline void RaftAppendEntries::set_term(::uint64_t value) {
  _internal_set_term(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.term)
}
inline ::uint64_t RaftAppendEntries::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void RaftAppendEntries::_internal_set_term(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// string leader_id = 2;
inline void RaftAppendEntries::clear_leader_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leader_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RaftAppendEntries::leader_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.leader_id)
  return _internal_leader_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RaftAppendEntries::set_leader_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.leader_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.leader_id)
}
inline ::std::string* PROTOBUF_NONNULL RaftAppendEntries::mutable_leader_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_leader_id();
  // @@protoc_insertion_point(field_mutable:coor.RaftAppendEntries.leader_id)
  return _s;
}
inline const ::std::string& RaftAppendEntries::_internal_leader_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leader_id_.Get();
}
inline void RaftAppendEntries::_internal_set_leader_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leader_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RaftAppendEntries::_internal_mutable_leader_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.leader_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RaftAppendEntries::release_leader_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:coor.RaftAppendEntries.leader_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.leader_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.leader_id_.Set("", GetArena());
  }
  return released;
}
inline void RaftAppendEntries::set_allocated_leader_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.leader_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.leader_id_.IsDefault()) {
    _impl_.leader_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:coor.RaftAppendEntries.leader_id)
}

// uint64 prev_log_index = 3;
inline void RaftAppendEntries::clear_prev_log_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prev_log_index_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t RaftAppendEntries::prev_log_index() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.prev_log_index)
  return _internal_prev_log_index();
}
inline void RaftAppendEntries::set_prev_log_index(::uint64_t value) {
  _internal_set_prev_log_index(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.prev_log_index)
}
inline ::uint64_t RaftAppendEntries::_internal_prev_log_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prev_log_index_;
}
inline void RaftAppendEntries::_internal_set_prev_log_index(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prev_log_index_ = value;
}

// uint64 prev_log_term = 4;
inline void RaftAppendEntries::clear_prev_log_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prev_log_term_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t RaftAppendEntries::prev_log_term() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.prev_log_term)
  return _internal_prev_log_term();
}
inline void RaftAppendEntries::set_prev_log_term(::uint64_t value) {
  _internal_set_prev_log_term(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.prev_log_term)
}
inline ::uint64_t RaftAppendEntries::_internal_prev_log_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prev_log_term_;
}
inline void RaftAppendEntries::_internal_set_prev_log_term(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prev_log_term_ = value;
}

// uint64 leader_commit = 5;
inline void RaftAppendEntries::clear_leader_commit() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leader_commit_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t RaftAppendEntries::leader_commit() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.leader_commit)
  return _internal_leader_commit();
}
inline void RaftAppendEntries::set_leader_commit(::uint64_t value) {
  _internal_set_leader_commit(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.leader_commit)
}
inline ::uint64_t RaftAppendEntries::_internal_leader_commit() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leader_commit_;
}
inline void RaftAppendEntries::_internal_set_leader_commit(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leader_commit_ = value;
}

// uint32 leader_next_node_id_alloc = 6;
inline void RaftAppendEntries::clear_leader_next_node_id_alloc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leader_next_node_id_alloc_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint32_t RaftAppendEntries::leader_next_node_id_alloc() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntries.leader_next_node_id_alloc)
  return _internal_leader_next_node_id_alloc();
}
inline void RaftAppendEntries::set_leader_next_node_id_alloc(::uint32_t value) {
  _internal_set_leader_next_node_id_alloc(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntries.leader_next_node_id_alloc)
}
inline ::uint32_t RaftAppendEntries::_internal_leader_next_node_id_alloc() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.leader_next_node_id_alloc_;
}
inline void RaftAppendEntries::_internal_set_leader_next_node_id_alloc(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.leader_next_node_id_alloc_ = value;
}

// -------------------------------------------------------------------

// RaftAppendEntriesRsp

// uint64 term = 1;
inline void RaftAppendEntriesRsp::clear_term() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t RaftAppendEntriesRsp::term() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntriesRsp.term)
  return _internal_term();
}
inline void RaftAppendEntriesRsp::set_term(::uint64_t value) {
  _internal_set_term(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntriesRsp.term)
}
inline ::uint64_t RaftAppendEntriesRsp::_internal_term() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.term_;
}
inline void RaftAppendEntriesRsp::_internal_set_term(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.term_ = value;
}

// bool success = 2;
inline void RaftAppendEntriesRsp::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool RaftAppendEntriesRsp::success() const {
  // @@protoc_insertion_point(field_get:coor.RaftAppendEntriesRsp.success)
  return _internal_success();
}
inline void RaftAppendEntriesRsp::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:coor.RaftAppendEntriesRsp.success)
}
inline bool RaftAppendEntriesRsp::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void RaftAppendEntriesRsp::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace coor


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // coor_2eproto_2epb_2eh
