// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_basic.proto

#ifndef PROTOBUF_INCLUDED_user_5fbasic_2eproto
#define PROTOBUF_INCLUDED_user_5fbasic_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_user_5fbasic_2eproto 

namespace protobuf_user_5fbasic_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_user_5fbasic_2eproto
namespace server {
class user_device_info_notify;
class user_device_info_notifyDefaultTypeInternal;
extern user_device_info_notifyDefaultTypeInternal _user_device_info_notify_default_instance_;
class user_device_info_notify_ack;
class user_device_info_notify_ackDefaultTypeInternal;
extern user_device_info_notify_ackDefaultTypeInternal _user_device_info_notify_ack_default_instance_;
}  // namespace server
namespace google {
namespace protobuf {
template<> ::server::user_device_info_notify* Arena::CreateMaybeMessage<::server::user_device_info_notify>(Arena*);
template<> ::server::user_device_info_notify_ack* Arena::CreateMaybeMessage<::server::user_device_info_notify_ack>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace server {

// ===================================================================

class user_device_info_notify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:server.user_device_info_notify) */ {
 public:
  user_device_info_notify();
  virtual ~user_device_info_notify();

  user_device_info_notify(const user_device_info_notify& from);

  inline user_device_info_notify& operator=(const user_device_info_notify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  user_device_info_notify(user_device_info_notify&& from) noexcept
    : user_device_info_notify() {
    *this = ::std::move(from);
  }

  inline user_device_info_notify& operator=(user_device_info_notify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const user_device_info_notify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const user_device_info_notify* internal_default_instance() {
    return reinterpret_cast<const user_device_info_notify*>(
               &_user_device_info_notify_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(user_device_info_notify* other);
  friend void swap(user_device_info_notify& a, user_device_info_notify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline user_device_info_notify* New() const final {
    return CreateMaybeMessage<user_device_info_notify>(NULL);
  }

  user_device_info_notify* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<user_device_info_notify>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const user_device_info_notify& from);
  void MergeFrom(const user_device_info_notify& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(user_device_info_notify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string devid = 2;
  void clear_devid();
  static const int kDevidFieldNumber = 2;
  const ::std::string& devid() const;
  void set_devid(const ::std::string& value);
  #if LANG_CXX11
  void set_devid(::std::string&& value);
  #endif
  void set_devid(const char* value);
  void set_devid(const char* value, size_t size);
  ::std::string* mutable_devid();
  ::std::string* release_devid();
  void set_allocated_devid(::std::string* devid);

  // string accNodeIdentify = 6;
  void clear_accnodeidentify();
  static const int kAccNodeIdentifyFieldNumber = 6;
  const ::std::string& accnodeidentify() const;
  void set_accnodeidentify(const ::std::string& value);
  #if LANG_CXX11
  void set_accnodeidentify(::std::string&& value);
  #endif
  void set_accnodeidentify(const char* value);
  void set_accnodeidentify(const char* value, size_t size);
  ::std::string* mutable_accnodeidentify();
  ::std::string* release_accnodeidentify();
  void set_allocated_accnodeidentify(::std::string* accnodeidentify);

  // int64 userId = 1;
  void clear_userid();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int64 userid() const;
  void set_userid(::google::protobuf::int64 value);

  // uint64 ssidFreshTime = 4;
  void clear_ssidfreshtime();
  static const int kSsidFreshTimeFieldNumber = 4;
  ::google::protobuf::uint64 ssidfreshtime() const;
  void set_ssidfreshtime(::google::protobuf::uint64 value);

  // uint64 sessionId = 5;
  void clear_sessionid();
  static const int kSessionIdFieldNumber = 5;
  ::google::protobuf::uint64 sessionid() const;
  void set_sessionid(::google::protobuf::uint64 value);

  // uint32 status = 3;
  void clear_status();
  static const int kStatusFieldNumber = 3;
  ::google::protobuf::uint32 status() const;
  void set_status(::google::protobuf::uint32 value);

  // uint32 loginTime = 7;
  void clear_logintime();
  static const int kLoginTimeFieldNumber = 7;
  ::google::protobuf::uint32 logintime() const;
  void set_logintime(::google::protobuf::uint32 value);

  // uint64 notify_groupid = 8;
  void clear_notify_groupid();
  static const int kNotifyGroupidFieldNumber = 8;
  ::google::protobuf::uint64 notify_groupid() const;
  void set_notify_groupid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:server.user_device_info_notify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr devid_;
  ::google::protobuf::internal::ArenaStringPtr accnodeidentify_;
  ::google::protobuf::int64 userid_;
  ::google::protobuf::uint64 ssidfreshtime_;
  ::google::protobuf::uint64 sessionid_;
  ::google::protobuf::uint32 status_;
  ::google::protobuf::uint32 logintime_;
  ::google::protobuf::uint64 notify_groupid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_user_5fbasic_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class user_device_info_notify_ack : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:server.user_device_info_notify_ack) */ {
 public:
  user_device_info_notify_ack();
  virtual ~user_device_info_notify_ack();

  user_device_info_notify_ack(const user_device_info_notify_ack& from);

  inline user_device_info_notify_ack& operator=(const user_device_info_notify_ack& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  user_device_info_notify_ack(user_device_info_notify_ack&& from) noexcept
    : user_device_info_notify_ack() {
    *this = ::std::move(from);
  }

  inline user_device_info_notify_ack& operator=(user_device_info_notify_ack&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const user_device_info_notify_ack& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const user_device_info_notify_ack* internal_default_instance() {
    return reinterpret_cast<const user_device_info_notify_ack*>(
               &_user_device_info_notify_ack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(user_device_info_notify_ack* other);
  friend void swap(user_device_info_notify_ack& a, user_device_info_notify_ack& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline user_device_info_notify_ack* New() const final {
    return CreateMaybeMessage<user_device_info_notify_ack>(NULL);
  }

  user_device_info_notify_ack* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<user_device_info_notify_ack>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const user_device_info_notify_ack& from);
  void MergeFrom(const user_device_info_notify_ack& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(user_device_info_notify_ack* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string codeMsg = 2;
  void clear_codemsg();
  static const int kCodeMsgFieldNumber = 2;
  const ::std::string& codemsg() const;
  void set_codemsg(const ::std::string& value);
  #if LANG_CXX11
  void set_codemsg(::std::string&& value);
  #endif
  void set_codemsg(const char* value);
  void set_codemsg(const char* value, size_t size);
  ::std::string* mutable_codemsg();
  ::std::string* release_codemsg();
  void set_allocated_codemsg(::std::string* codemsg);

  // uint32 code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::google::protobuf::uint32 code() const;
  void set_code(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:server.user_device_info_notify_ack)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr codemsg_;
  ::google::protobuf::uint32 code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_user_5fbasic_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// user_device_info_notify

// int64 userId = 1;
inline void user_device_info_notify::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 user_device_info_notify::userid() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.userId)
  return userid_;
}
inline void user_device_info_notify::set_userid(::google::protobuf::int64 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.userId)
}

// string devid = 2;
inline void user_device_info_notify::clear_devid() {
  devid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& user_device_info_notify::devid() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.devid)
  return devid_.GetNoArena();
}
inline void user_device_info_notify::set_devid(const ::std::string& value) {
  
  devid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.devid)
}
#if LANG_CXX11
inline void user_device_info_notify::set_devid(::std::string&& value) {
  
  devid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:server.user_device_info_notify.devid)
}
#endif
inline void user_device_info_notify::set_devid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  devid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:server.user_device_info_notify.devid)
}
inline void user_device_info_notify::set_devid(const char* value, size_t size) {
  
  devid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:server.user_device_info_notify.devid)
}
inline ::std::string* user_device_info_notify::mutable_devid() {
  
  // @@protoc_insertion_point(field_mutable:server.user_device_info_notify.devid)
  return devid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* user_device_info_notify::release_devid() {
  // @@protoc_insertion_point(field_release:server.user_device_info_notify.devid)
  
  return devid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void user_device_info_notify::set_allocated_devid(::std::string* devid) {
  if (devid != NULL) {
    
  } else {
    
  }
  devid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), devid);
  // @@protoc_insertion_point(field_set_allocated:server.user_device_info_notify.devid)
}

// uint32 status = 3;
inline void user_device_info_notify::clear_status() {
  status_ = 0u;
}
inline ::google::protobuf::uint32 user_device_info_notify::status() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.status)
  return status_;
}
inline void user_device_info_notify::set_status(::google::protobuf::uint32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.status)
}

// uint64 ssidFreshTime = 4;
inline void user_device_info_notify::clear_ssidfreshtime() {
  ssidfreshtime_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 user_device_info_notify::ssidfreshtime() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.ssidFreshTime)
  return ssidfreshtime_;
}
inline void user_device_info_notify::set_ssidfreshtime(::google::protobuf::uint64 value) {
  
  ssidfreshtime_ = value;
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.ssidFreshTime)
}

// uint64 sessionId = 5;
inline void user_device_info_notify::clear_sessionid() {
  sessionid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 user_device_info_notify::sessionid() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.sessionId)
  return sessionid_;
}
inline void user_device_info_notify::set_sessionid(::google::protobuf::uint64 value) {
  
  sessionid_ = value;
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.sessionId)
}

// string accNodeIdentify = 6;
inline void user_device_info_notify::clear_accnodeidentify() {
  accnodeidentify_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& user_device_info_notify::accnodeidentify() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.accNodeIdentify)
  return accnodeidentify_.GetNoArena();
}
inline void user_device_info_notify::set_accnodeidentify(const ::std::string& value) {
  
  accnodeidentify_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.accNodeIdentify)
}
#if LANG_CXX11
inline void user_device_info_notify::set_accnodeidentify(::std::string&& value) {
  
  accnodeidentify_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:server.user_device_info_notify.accNodeIdentify)
}
#endif
inline void user_device_info_notify::set_accnodeidentify(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  accnodeidentify_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:server.user_device_info_notify.accNodeIdentify)
}
inline void user_device_info_notify::set_accnodeidentify(const char* value, size_t size) {
  
  accnodeidentify_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:server.user_device_info_notify.accNodeIdentify)
}
inline ::std::string* user_device_info_notify::mutable_accnodeidentify() {
  
  // @@protoc_insertion_point(field_mutable:server.user_device_info_notify.accNodeIdentify)
  return accnodeidentify_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* user_device_info_notify::release_accnodeidentify() {
  // @@protoc_insertion_point(field_release:server.user_device_info_notify.accNodeIdentify)
  
  return accnodeidentify_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void user_device_info_notify::set_allocated_accnodeidentify(::std::string* accnodeidentify) {
  if (accnodeidentify != NULL) {
    
  } else {
    
  }
  accnodeidentify_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), accnodeidentify);
  // @@protoc_insertion_point(field_set_allocated:server.user_device_info_notify.accNodeIdentify)
}

// uint32 loginTime = 7;
inline void user_device_info_notify::clear_logintime() {
  logintime_ = 0u;
}
inline ::google::protobuf::uint32 user_device_info_notify::logintime() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.loginTime)
  return logintime_;
}
inline void user_device_info_notify::set_logintime(::google::protobuf::uint32 value) {
  
  logintime_ = value;
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.loginTime)
}

// uint64 notify_groupid = 8;
inline void user_device_info_notify::clear_notify_groupid() {
  notify_groupid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 user_device_info_notify::notify_groupid() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.notify_groupid)
  return notify_groupid_;
}
inline void user_device_info_notify::set_notify_groupid(::google::protobuf::uint64 value) {
  
  notify_groupid_ = value;
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.notify_groupid)
}

// -------------------------------------------------------------------

// user_device_info_notify_ack

// uint32 code = 1;
inline void user_device_info_notify_ack::clear_code() {
  code_ = 0u;
}
inline ::google::protobuf::uint32 user_device_info_notify_ack::code() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify_ack.code)
  return code_;
}
inline void user_device_info_notify_ack::set_code(::google::protobuf::uint32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:server.user_device_info_notify_ack.code)
}

// string codeMsg = 2;
inline void user_device_info_notify_ack::clear_codemsg() {
  codemsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& user_device_info_notify_ack::codemsg() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify_ack.codeMsg)
  return codemsg_.GetNoArena();
}
inline void user_device_info_notify_ack::set_codemsg(const ::std::string& value) {
  
  codemsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify_ack.codeMsg)
}
#if LANG_CXX11
inline void user_device_info_notify_ack::set_codemsg(::std::string&& value) {
  
  codemsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:server.user_device_info_notify_ack.codeMsg)
}
#endif
inline void user_device_info_notify_ack::set_codemsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  codemsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:server.user_device_info_notify_ack.codeMsg)
}
inline void user_device_info_notify_ack::set_codemsg(const char* value, size_t size) {
  
  codemsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:server.user_device_info_notify_ack.codeMsg)
}
inline ::std::string* user_device_info_notify_ack::mutable_codemsg() {
  
  // @@protoc_insertion_point(field_mutable:server.user_device_info_notify_ack.codeMsg)
  return codemsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* user_device_info_notify_ack::release_codemsg() {
  // @@protoc_insertion_point(field_release:server.user_device_info_notify_ack.codeMsg)
  
  return codemsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void user_device_info_notify_ack::set_allocated_codemsg(::std::string* codemsg) {
  if (codemsg != NULL) {
    
  } else {
    
  }
  codemsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), codemsg);
  // @@protoc_insertion_point(field_set_allocated:server.user_device_info_notify_ack.codeMsg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace server

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_user_5fbasic_2eproto
