// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_basic.proto
// Protobuf C++ Version: 7.35.0-dev

#include "user_basic.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::server::user_device_info_notify
        {&::_pbi::kDescriptorMethods, &::descriptor_table_user_5fbasic_2eproto, /* tracker*/ nullptr,},
        // ::server::user_device_info_notify_ack
        {&::_pbi::kDescriptorMethods, &::descriptor_table_user_5fbasic_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace server {

inline constexpr user_device_info_notify_ack::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        codemsg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        code_{0u} {}

template <typename>
constexpr user_device_info_notify_ack::user_device_info_notify_ack(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(user_device_info_notify_ack_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct user_device_info_notify_ackGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr user_device_info_notify_ackGlobalsTypeInternal() : _default(::_pbi::ConstantInitialized{}) {}
  ~user_device_info_notify_ackGlobalsTypeInternal() {}
  union {
    user_device_info_notify_ack _default;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 user_device_info_notify_ackGlobalsTypeInternal _user_device_info_notify_ack_globals_;

inline constexpr user_device_info_notify::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        devid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        accnodeidentify_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        userid_{::int64_t{0}},
        ssidfreshtime_{::uint64_t{0u}},
        sessionid_{::uint64_t{0u}},
        status_{0u},
        logintime_{0u},
        notify_groupid_{::uint64_t{0u}} {}

template <typename>
constexpr user_device_info_notify::user_device_info_notify(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(user_device_info_notify_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct user_device_info_notifyGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr user_device_info_notifyGlobalsTypeInternal() : _default(::_pbi::ConstantInitialized{}) {}
  ~user_device_info_notifyGlobalsTypeInternal() {}
  union {
    user_device_info_notify _default;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 user_device_info_notifyGlobalsTypeInternal _user_device_info_notify_globals_;
}  // namespace server
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_user_5fbasic_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_user_5fbasic_2eproto = nullptr;
const ::uint32_t
    TableStruct_user_5fbasic_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify, _impl_.devid_),
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify, _impl_.ssidfreshtime_),
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify, _impl_.sessionid_),
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify, _impl_.accnodeidentify_),
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify, _impl_.logintime_),
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify, _impl_.notify_groupid_),
        2,
        0,
        5,
        3,
        4,
        1,
        6,
        7,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify_ack, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify_ack, _impl_.code_),
        PROTOBUF_FIELD_OFFSET(::server::user_device_info_notify_ack, _impl_.codemsg_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::server::user_device_info_notify)},
        {19, sizeof(::server::user_device_info_notify_ack)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::server::_user_device_info_notify_globals_,
        &::server::_user_device_info_notify_ack_globals_,
};
const char descriptor_table_protodef_user_5fbasic_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020user_basic.proto\022\006server\"\266\001\n\027user_devi"
    "ce_info_notify\022\016\n\006userId\030\001 \001(\003\022\r\n\005devid\030"
    "\002 \001(\t\022\016\n\006status\030\003 \001(\r\022\025\n\rssidFreshTime\030\004"
    " \001(\004\022\021\n\tsessionId\030\005 \001(\004\022\027\n\017accNodeIdenti"
    "fy\030\006 \001(\t\022\021\n\tloginTime\030\007 \001(\r\022\026\n\016notify_gr"
    "oupid\030\010 \001(\004\"<\n\033user_device_info_notify_a"
    "ck\022\014\n\004code\030\001 \001(\r\022\017\n\007codeMsg\030\002 \001(\tb\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_user_5fbasic_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_user_5fbasic_2eproto = {
    false,
    false,
    281,
    descriptor_table_protodef_user_5fbasic_2eproto,
    "user_basic.proto",
    &descriptor_table_user_5fbasic_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_message_globals,
    TableStruct_user_5fbasic_2eproto::offsets,
    file_level_enum_descriptors_user_5fbasic_2eproto,
    file_level_service_descriptors_user_5fbasic_2eproto,
};
namespace server {
// ===================================================================

class user_device_info_notify::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<user_device_info_notify>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_._has_bits_);
};

user_device_info_notify::user_device_info_notify(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, user_device_info_notify_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:server.user_device_info_notify)
}
PROTOBUF_NDEBUG_INLINE user_device_info_notify::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::server::user_device_info_notify& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        devid_(arena, from.devid_),
        accnodeidentify_(arena, from.accnodeidentify_) {}

user_device_info_notify::user_device_info_notify(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const user_device_info_notify& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, user_device_info_notify_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  user_device_info_notify* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, userid_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, userid_),
           offsetof(Impl_, notify_groupid_) -
               offsetof(Impl_, userid_) +
               sizeof(Impl_::notify_groupid_));

  // @@protoc_insertion_point(copy_constructor:server.user_device_info_notify)
}
PROTOBUF_NDEBUG_INLINE user_device_info_notify::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        devid_(arena),
        accnodeidentify_(arena) {}

inline void user_device_info_notify::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, userid_),
           0,
           offsetof(Impl_, notify_groupid_) -
               offsetof(Impl_, userid_) +
               sizeof(Impl_::notify_groupid_));
}
user_device_info_notify::~user_device_info_notify() {
  // @@protoc_insertion_point(destructor:server.user_device_info_notify)
  SharedDtor(*this);
}
inline void user_device_info_notify::SharedDtor(MessageLite& self) {
  user_device_info_notify& this_ = static_cast<user_device_info_notify&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.devid_.Destroy();
  this_._impl_.accnodeidentify_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL user_device_info_notify::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) user_device_info_notify(arena);
}
constexpr auto user_device_info_notify::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(user_device_info_notify),
                                            alignof(user_device_info_notify));
}
constexpr auto user_device_info_notify::InternalGenerateClassData_() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_user_device_info_notify_globals_._default,
          &_table_.header,
          nullptr,  // IsInitialized
          &user_device_info_notify::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<user_device_info_notify>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &user_device_info_notify::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<user_device_info_notify>(), &user_device_info_notify::ByteSizeLong,
              &user_device_info_notify::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_._cached_size_),
          false,
      },
      &file_reflection_data[0]};
#else  // !PROTOBUF_MESSAGE_GLOBALS
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_user_device_info_notify_globals_._default,
          &_table_.header,
          nullptr,  // IsInitialized
          &user_device_info_notify::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<user_device_info_notify>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &user_device_info_notify::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<user_device_info_notify>(), &user_device_info_notify::ByteSizeLong,
              &user_device_info_notify::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_._cached_size_),
          false,
      },
      &::_pbi::kDescriptorMethods,
      &descriptor_table_user_5fbasic_2eproto,
      nullptr,  // tracker
  };
#endif  // PROTOBUF_MESSAGE_GLOBALS
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull user_device_info_notify_class_data_ =
        user_device_info_notify::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
user_device_info_notify::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&user_device_info_notify_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(user_device_info_notify_class_data_.tc_table);
  return user_device_info_notify_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 67, 2>
user_device_info_notify::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    user_device_info_notify_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::server::user_device_info_notify>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 notify_groupid = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(user_device_info_notify, _impl_.notify_groupid_), 7>(),
     {64, 7, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.notify_groupid_)}},
    // int64 userId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(user_device_info_notify, _impl_.userid_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.userid_)}},
    // string devid = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.devid_)}},
    // uint32 status = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(user_device_info_notify, _impl_.status_), 5>(),
     {24, 5, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.status_)}},
    // uint64 ssidFreshTime = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(user_device_info_notify, _impl_.ssidfreshtime_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.ssidfreshtime_)}},
    // uint64 sessionId = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(user_device_info_notify, _impl_.sessionid_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.sessionid_)}},
    // string accNodeIdentify = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 1, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.accnodeidentify_)}},
    // uint32 loginTime = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(user_device_info_notify, _impl_.logintime_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.logintime_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 userId = 1;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.userid_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // string devid = 2;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.devid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 status = 3;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.status_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint64 ssidFreshTime = 4;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.ssidfreshtime_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 sessionId = 5;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.sessionid_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // string accNodeIdentify = 6;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.accnodeidentify_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 loginTime = 7;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.logintime_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint64 notify_groupid = 8;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.notify_groupid_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
    "\36\0\5\0\0\0\17\0\0\0\0\0\0\0\0\0"
    "server.user_device_info_notify"
    "devid"
    "accNodeIdentify"
  }},
};
PROTOBUF_NOINLINE void user_device_info_notify::Clear() {
// @@protoc_insertion_point(message_clear_start:server.user_device_info_notify)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.devid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.accnodeidentify_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000fcU)) {
    ::memset(&_impl_.userid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.notify_groupid_) -
        reinterpret_cast<char*>(&_impl_.userid_)) + sizeof(_impl_.notify_groupid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL user_device_info_notify::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const user_device_info_notify& this_ = static_cast<const user_device_info_notify&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL user_device_info_notify::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const user_device_info_notify& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:server.user_device_info_notify)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int64 userId = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_userid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_userid(), target);
    }
  }

  // string devid = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_devid().empty()) {
      const ::std::string& _s = this_._internal_devid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "server.user_device_info_notify.devid");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // uint32 status = 3;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_status(), target);
    }
  }

  // uint64 ssidFreshTime = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_ssidfreshtime() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_ssidfreshtime(), target);
    }
  }

  // uint64 sessionId = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_sessionid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          5, this_._internal_sessionid(), target);
    }
  }

  // string accNodeIdentify = 6;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_accnodeidentify().empty()) {
      const ::std::string& _s = this_._internal_accnodeidentify();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "server.user_device_info_notify.accNodeIdentify");
      target = stream->WriteStringMaybeAliased(6, _s, target);
    }
  }

  // uint32 loginTime = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_logintime() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          7, this_._internal_logintime(), target);
    }
  }

  // uint64 notify_groupid = 8;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_notify_groupid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          8, this_._internal_notify_groupid(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:server.user_device_info_notify)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t user_device_info_notify::ByteSizeLong(const MessageLite& base) {
  const user_device_info_notify& this_ = static_cast<const user_device_info_notify&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t user_device_info_notify::ByteSizeLong() const {
  const user_device_info_notify& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:server.user_device_info_notify)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string devid = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_devid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_devid());
      }
    }
    // string accNodeIdentify = 6;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_accnodeidentify().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_accnodeidentify());
      }
    }
    // int64 userId = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_userid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_userid());
      }
    }
    // uint64 ssidFreshTime = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_ssidfreshtime() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_ssidfreshtime());
      }
    }
    // uint64 sessionId = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_sessionid() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_sessionid());
      }
    }
    // uint32 status = 3;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_status() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_status());
      }
    }
    // uint32 loginTime = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_logintime() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_logintime());
      }
    }
    // uint64 notify_groupid = 8;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_notify_groupid() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_notify_groupid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void user_device_info_notify::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<user_device_info_notify*>(&to_msg);
  auto& from = static_cast<const user_device_info_notify&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:server.user_device_info_notify)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_devid().empty()) {
        _this->_internal_set_devid(from._internal_devid());
      } else {
        if (_this->_impl_.devid_.IsDefault()) {
          _this->_internal_set_devid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_accnodeidentify().empty()) {
        _this->_internal_set_accnodeidentify(from._internal_accnodeidentify());
      } else {
        if (_this->_impl_.accnodeidentify_.IsDefault()) {
          _this->_internal_set_accnodeidentify("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_userid() != 0) {
        _this->_impl_.userid_ = from._impl_.userid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_ssidfreshtime() != 0) {
        _this->_impl_.ssidfreshtime_ = from._impl_.ssidfreshtime_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_sessionid() != 0) {
        _this->_impl_.sessionid_ = from._impl_.sessionid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_logintime() != 0) {
        _this->_impl_.logintime_ = from._impl_.logintime_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_notify_groupid() != 0) {
        _this->_impl_.notify_groupid_ = from._impl_.notify_groupid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void user_device_info_notify::CopyFrom(const user_device_info_notify& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:server.user_device_info_notify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void user_device_info_notify::InternalSwap(user_device_info_notify* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.devid_, &other->_impl_.devid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.accnodeidentify_, &other->_impl_.accnodeidentify_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.notify_groupid_)
      + sizeof(user_device_info_notify::_impl_.notify_groupid_)
      - PROTOBUF_FIELD_OFFSET(user_device_info_notify, _impl_.userid_)>(
          reinterpret_cast<char*>(&_impl_.userid_),
          reinterpret_cast<char*>(&other->_impl_.userid_));
}

::google::protobuf::Metadata user_device_info_notify::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class user_device_info_notify_ack::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<user_device_info_notify_ack>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(user_device_info_notify_ack, _impl_._has_bits_);
};

user_device_info_notify_ack::user_device_info_notify_ack(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, user_device_info_notify_ack_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:server.user_device_info_notify_ack)
}
PROTOBUF_NDEBUG_INLINE user_device_info_notify_ack::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::server::user_device_info_notify_ack& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        codemsg_(arena, from.codemsg_) {}

user_device_info_notify_ack::user_device_info_notify_ack(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const user_device_info_notify_ack& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, user_device_info_notify_ack_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  user_device_info_notify_ack* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.code_ = from._impl_.code_;

  // @@protoc_insertion_point(copy_constructor:server.user_device_info_notify_ack)
}
PROTOBUF_NDEBUG_INLINE user_device_info_notify_ack::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        codemsg_(arena) {}

inline void user_device_info_notify_ack::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.code_ = {};
}
user_device_info_notify_ack::~user_device_info_notify_ack() {
  // @@protoc_insertion_point(destructor:server.user_device_info_notify_ack)
  SharedDtor(*this);
}
inline void user_device_info_notify_ack::SharedDtor(MessageLite& self) {
  user_device_info_notify_ack& this_ = static_cast<user_device_info_notify_ack&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.codemsg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL user_device_info_notify_ack::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) user_device_info_notify_ack(arena);
}
constexpr auto user_device_info_notify_ack::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(user_device_info_notify_ack),
                                            alignof(user_device_info_notify_ack));
}
constexpr auto user_device_info_notify_ack::InternalGenerateClassData_() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_user_device_info_notify_ack_globals_._default,
          &_table_.header,
          nullptr,  // IsInitialized
          &user_device_info_notify_ack::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<user_device_info_notify_ack>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &user_device_info_notify_ack::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<user_device_info_notify_ack>(), &user_device_info_notify_ack::ByteSizeLong,
              &user_device_info_notify_ack::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(user_device_info_notify_ack, _impl_._cached_size_),
          false,
      },
      &file_reflection_data[1]};
#else  // !PROTOBUF_MESSAGE_GLOBALS
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_user_device_info_notify_ack_globals_._default,
          &_table_.header,
          nullptr,  // IsInitialized
          &user_device_info_notify_ack::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<user_device_info_notify_ack>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &user_device_info_notify_ack::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<user_device_info_notify_ack>(), &user_device_info_notify_ack::ByteSizeLong,
              &user_device_info_notify_ack::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(user_device_info_notify_ack, _impl_._cached_size_),
          false,
      },
      &::_pbi::kDescriptorMethods,
      &descriptor_table_user_5fbasic_2eproto,
      nullptr,  // tracker
  };
#endif  // PROTOBUF_MESSAGE_GLOBALS
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull user_device_info_notify_ack_class_data_ =
        user_device_info_notify_ack::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
user_device_info_notify_ack::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&user_device_info_notify_ack_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(user_device_info_notify_ack_class_data_.tc_table);
  return user_device_info_notify_ack_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 50, 2>
user_device_info_notify_ack::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(user_device_info_notify_ack, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    user_device_info_notify_ack_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::server::user_device_info_notify_ack>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string codeMsg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify_ack, _impl_.codemsg_)}},
    // uint32 code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(user_device_info_notify_ack, _impl_.code_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(user_device_info_notify_ack, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 code = 1;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify_ack, _impl_.code_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // string codeMsg = 2;
    {PROTOBUF_FIELD_OFFSET(user_device_info_notify_ack, _impl_.codemsg_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\0\7\0\0\0\0\0"
    "server.user_device_info_notify_ack"
    "codeMsg"
  }},
};
PROTOBUF_NOINLINE void user_device_info_notify_ack::Clear() {
// @@protoc_insertion_point(message_clear_start:server.user_device_info_notify_ack)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.codemsg_.ClearNonDefaultToEmpty();
  }
  _impl_.code_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL user_device_info_notify_ack::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const user_device_info_notify_ack& this_ = static_cast<const user_device_info_notify_ack&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL user_device_info_notify_ack::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const user_device_info_notify_ack& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:server.user_device_info_notify_ack)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 code = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_code() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_code(), target);
    }
  }

  // string codeMsg = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_codemsg().empty()) {
      const ::std::string& _s = this_._internal_codemsg();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "server.user_device_info_notify_ack.codeMsg");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:server.user_device_info_notify_ack)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t user_device_info_notify_ack::ByteSizeLong(const MessageLite& base) {
  const user_device_info_notify_ack& this_ = static_cast<const user_device_info_notify_ack&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t user_device_info_notify_ack::ByteSizeLong() const {
  const user_device_info_notify_ack& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:server.user_device_info_notify_ack)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string codeMsg = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_codemsg().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_codemsg());
      }
    }
    // uint32 code = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_code() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_code());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void user_device_info_notify_ack::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<user_device_info_notify_ack*>(&to_msg);
  auto& from = static_cast<const user_device_info_notify_ack&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:server.user_device_info_notify_ack)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_codemsg().empty()) {
        _this->_internal_set_codemsg(from._internal_codemsg());
      } else {
        if (_this->_impl_.codemsg_.IsDefault()) {
          _this->_internal_set_codemsg("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_code() != 0) {
        _this->_impl_.code_ = from._impl_.code_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void user_device_info_notify_ack::CopyFrom(const user_device_info_notify_ack& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:server.user_device_info_notify_ack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void user_device_info_notify_ack::InternalSwap(user_device_info_notify_ack* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.codemsg_, &other->_impl_.codemsg_, arena);
  swap(_impl_.code_, other->_impl_.code_);
}

::google::protobuf::Metadata user_device_info_notify_ack::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace server
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_user_5fbasic_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
