// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_basic.proto
// Protobuf C++ Version: 7.35.0-dev

#ifndef user_5fbasic_2eproto_2epb_2eh
#define user_5fbasic_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_user_5fbasic_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_user_5fbasic_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_user_5fbasic_2eproto;
}  // extern "C"
namespace server {
class user_device_info_notify;
struct user_device_info_notifyGlobalsTypeInternal;
extern user_device_info_notifyGlobalsTypeInternal _user_device_info_notify_globals_;
extern const ::google::protobuf::internal::ClassDataFull user_device_info_notify_class_data_;
class user_device_info_notify_ack;
struct user_device_info_notify_ackGlobalsTypeInternal;
extern user_device_info_notify_ackGlobalsTypeInternal _user_device_info_notify_ack_globals_;
extern const ::google::protobuf::internal::ClassDataFull user_device_info_notify_ack_class_data_;
}  // namespace server
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace server {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED user_device_info_notify_ack final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:server.user_device_info_notify_ack) */ {
 public:
  inline user_device_info_notify_ack() : user_device_info_notify_ack(nullptr) {}
  ~user_device_info_notify_ack() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(user_device_info_notify_ack* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(user_device_info_notify_ack));
  }
#endif

  template <typename = void>
  explicit constexpr user_device_info_notify_ack(::google::protobuf::internal::ConstantInitialized);

  inline user_device_info_notify_ack(const user_device_info_notify_ack& from) : user_device_info_notify_ack(nullptr, from) {}
  inline user_device_info_notify_ack(user_device_info_notify_ack&& from) noexcept
      : user_device_info_notify_ack(nullptr, ::std::move(from)) {}
  inline user_device_info_notify_ack& operator=(const user_device_info_notify_ack& from) {
    CopyFrom(from);
    return *this;
  }
  inline user_device_info_notify_ack& operator=(user_device_info_notify_ack&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const user_device_info_notify_ack& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::default_instance<user_device_info_notify_ack>(
        &_user_device_info_notify_ack_globals_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(user_device_info_notify_ack& a, user_device_info_notify_ack& b) { a.Swap(&b); }
  inline void Swap(user_device_info_notify_ack* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(user_device_info_notify_ack* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] user_device_info_notify_ack* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<user_device_info_notify_ack>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const user_device_info_notify_ack& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const user_device_info_notify_ack& from) { user_device_info_notify_ack::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(user_device_info_notify_ack* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "server.user_device_info_notify_ack"; }

  explicit user_device_info_notify_ack(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  user_device_info_notify_ack(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const user_device_info_notify_ack& from);
  user_device_info_notify_ack(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, user_device_info_notify_ack&& from) noexcept
      : user_device_info_notify_ack(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCodeMsgFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string codeMsg = 2;
  void clear_codemsg() ;
  [[nodiscard]] const ::std::string& codemsg() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_codemsg(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_codemsg();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_codemsg();
  void set_allocated_codemsg(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_codemsg() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_codemsg(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_codemsg();

  public:
  // uint32 code = 1;
  void clear_code() ;
  [[nodiscard]] ::uint32_t code() const;
  void set_code(::uint32_t value);

  private:
  ::uint32_t _internal_code() const;
  void _internal_set_code(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:server.user_device_info_notify_ack)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 50,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const user_device_info_notify_ack& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr codemsg_;
    ::uint32_t code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_user_5fbasic_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull user_device_info_notify_ack_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED user_device_info_notify final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:server.user_device_info_notify) */ {
 public:
  inline user_device_info_notify() : user_device_info_notify(nullptr) {}
  ~user_device_info_notify() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(user_device_info_notify* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(user_device_info_notify));
  }
#endif

  template <typename = void>
  explicit constexpr user_device_info_notify(::google::protobuf::internal::ConstantInitialized);

  inline user_device_info_notify(const user_device_info_notify& from) : user_device_info_notify(nullptr, from) {}
  inline user_device_info_notify(user_device_info_notify&& from) noexcept
      : user_device_info_notify(nullptr, ::std::move(from)) {}
  inline user_device_info_notify& operator=(const user_device_info_notify& from) {
    CopyFrom(from);
    return *this;
  }
  inline user_device_info_notify& operator=(user_device_info_notify&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const user_device_info_notify& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::default_instance<user_device_info_notify>(
        &_user_device_info_notify_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(user_device_info_notify& a, user_device_info_notify& b) { a.Swap(&b); }
  inline void Swap(user_device_info_notify* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(user_device_info_notify* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] user_device_info_notify* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<user_device_info_notify>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const user_device_info_notify& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const user_device_info_notify& from) { user_device_info_notify::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(user_device_info_notify* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "server.user_device_info_notify"; }

  explicit user_device_info_notify(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  user_device_info_notify(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const user_device_info_notify& from);
  user_device_info_notify(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, user_device_info_notify&& from) noexcept
      : user_device_info_notify(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDevidFieldNumber = 2,
    kAccNodeIdentifyFieldNumber = 6,
    kUserIdFieldNumber = 1,
    kSsidFreshTimeFieldNumber = 4,
    kSessionIdFieldNumber = 5,
    kStatusFieldNumber = 3,
    kLoginTimeFieldNumber = 7,
    kNotifyGroupidFieldNumber = 8,
  };
  // string devid = 2;
  void clear_devid() ;
  [[nodiscard]] const ::std::string& devid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_devid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_devid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_devid();
  void set_allocated_devid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_devid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_devid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_devid();

  public:
  // string accNodeIdentify = 6;
  void clear_accnodeidentify() ;
  [[nodiscard]] const ::std::string& accnodeidentify() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_accnodeidentify(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_accnodeidentify();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_accnodeidentify();
  void set_allocated_accnodeidentify(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_accnodeidentify() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_accnodeidentify(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_accnodeidentify();

  public:
  // int64 userId = 1;
  void clear_userid() ;
  [[nodiscard]] ::int64_t userid() const;
  void set_userid(::int64_t value);

  private:
  ::int64_t _internal_userid() const;
  void _internal_set_userid(::int64_t value);

  public:
  // uint64 ssidFreshTime = 4;
  void clear_ssidfreshtime() ;
  [[nodiscard]] ::uint64_t ssidfreshtime() const;
  void set_ssidfreshtime(::uint64_t value);

  private:
  ::uint64_t _internal_ssidfreshtime() const;
  void _internal_set_ssidfreshtime(::uint64_t value);

  public:
  // uint64 sessionId = 5;
  void clear_sessionid() ;
  [[nodiscard]] ::uint64_t sessionid() const;
  void set_sessionid(::uint64_t value);

  private:
  ::uint64_t _internal_sessionid() const;
  void _internal_set_sessionid(::uint64_t value);

  public:
  // uint32 status = 3;
  void clear_status() ;
  [[nodiscard]] ::uint32_t status() const;
  void set_status(::uint32_t value);

  private:
  ::uint32_t _internal_status() const;
  void _internal_set_status(::uint32_t value);

  public:
  // uint32 loginTime = 7;
  void clear_logintime() ;
  [[nodiscard]] ::uint32_t logintime() const;
  void set_logintime(::uint32_t value);

  private:
  ::uint32_t _internal_logintime() const;
  void _internal_set_logintime(::uint32_t value);

  public:
  // uint64 notify_groupid = 8;
  void clear_notify_groupid() ;
  [[nodiscard]] ::uint64_t notify_groupid() const;
  void set_notify_groupid(::uint64_t value);

  private:
  ::uint64_t _internal_notify_groupid() const;
  void _internal_set_notify_groupid(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:server.user_device_info_notify)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 67,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const user_device_info_notify& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr devid_;
    ::google::protobuf::internal::ArenaStringPtr accnodeidentify_;
    ::int64_t userid_;
    ::uint64_t ssidfreshtime_;
    ::uint64_t sessionid_;
    ::uint32_t status_;
    ::uint32_t logintime_;
    ::uint64_t notify_groupid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_user_5fbasic_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull user_device_info_notify_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// user_device_info_notify

// int64 userId = 1;
inline void user_device_info_notify::clear_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int64_t user_device_info_notify::userid() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.userId)
  return _internal_userid();
}
inline void user_device_info_notify::set_userid(::int64_t value) {
  _internal_set_userid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.userId)
}
inline ::int64_t user_device_info_notify::_internal_userid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.userid_;
}
inline void user_device_info_notify::_internal_set_userid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.userid_ = value;
}

// string devid = 2;
inline void user_device_info_notify::clear_devid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.devid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& user_device_info_notify::devid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.devid)
  return _internal_devid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void user_device_info_notify::set_devid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.devid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.devid)
}
inline ::std::string* PROTOBUF_NONNULL user_device_info_notify::mutable_devid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_devid();
  // @@protoc_insertion_point(field_mutable:server.user_device_info_notify.devid)
  return _s;
}
inline const ::std::string& user_device_info_notify::_internal_devid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.devid_.Get();
}
inline void user_device_info_notify::_internal_set_devid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.devid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL user_device_info_notify::_internal_mutable_devid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.devid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE user_device_info_notify::release_devid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:server.user_device_info_notify.devid)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.devid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.devid_.Set("", GetArena());
  }
  return released;
}
inline void user_device_info_notify::set_allocated_devid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.devid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.devid_.IsDefault()) {
    _impl_.devid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:server.user_device_info_notify.devid)
}

// uint32 status = 3;
inline void user_device_info_notify::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint32_t user_device_info_notify::status() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.status)
  return _internal_status();
}
inline void user_device_info_notify::set_status(::uint32_t value) {
  _internal_set_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.status)
}
inline ::uint32_t user_device_info_notify::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void user_device_info_notify::_internal_set_status(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// uint64 ssidFreshTime = 4;
inline void user_device_info_notify::clear_ssidfreshtime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ssidfreshtime_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t user_device_info_notify::ssidfreshtime() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.ssidFreshTime)
  return _internal_ssidfreshtime();
}
inline void user_device_info_notify::set_ssidfreshtime(::uint64_t value) {
  _internal_set_ssidfreshtime(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.ssidFreshTime)
}
inline ::uint64_t user_device_info_notify::_internal_ssidfreshtime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ssidfreshtime_;
}
inline void user_device_info_notify::_internal_set_ssidfreshtime(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ssidfreshtime_ = value;
}

// uint64 sessionId = 5;
inline void user_device_info_notify::clear_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t user_device_info_notify::sessionid() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.sessionId)
  return _internal_sessionid();
}
inline void user_device_info_notify::set_sessionid(::uint64_t value) {
  _internal_set_sessionid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.sessionId)
}
inline ::uint64_t user_device_info_notify::_internal_sessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sessionid_;
}
inline void user_device_info_notify::_internal_set_sessionid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_ = value;
}

// string accNodeIdentify = 6;
inline void user_device_info_notify::clear_accnodeidentify() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accnodeidentify_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& user_device_info_notify::accnodeidentify() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.accNodeIdentify)
  return _internal_accnodeidentify();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void user_device_info_notify::set_accnodeidentify(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.accnodeidentify_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.accNodeIdentify)
}
inline ::std::string* PROTOBUF_NONNULL user_device_info_notify::mutable_accnodeidentify()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_accnodeidentify();
  // @@protoc_insertion_point(field_mutable:server.user_device_info_notify.accNodeIdentify)
  return _s;
}
inline const ::std::string& user_device_info_notify::_internal_accnodeidentify() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.accnodeidentify_.Get();
}
inline void user_device_info_notify::_internal_set_accnodeidentify(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accnodeidentify_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL user_device_info_notify::_internal_mutable_accnodeidentify() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.accnodeidentify_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE user_device_info_notify::release_accnodeidentify() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:server.user_device_info_notify.accNodeIdentify)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.accnodeidentify_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.accnodeidentify_.Set("", GetArena());
  }
  return released;
}
inline void user_device_info_notify::set_allocated_accnodeidentify(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.accnodeidentify_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.accnodeidentify_.IsDefault()) {
    _impl_.accnodeidentify_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:server.user_device_info_notify.accNodeIdentify)
}

// uint32 loginTime = 7;
inline void user_device_info_notify::clear_logintime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.logintime_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint32_t user_device_info_notify::logintime() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.loginTime)
  return _internal_logintime();
}
inline void user_device_info_notify::set_logintime(::uint32_t value) {
  _internal_set_logintime(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.loginTime)
}
inline ::uint32_t user_device_info_notify::_internal_logintime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.logintime_;
}
inline void user_device_info_notify::_internal_set_logintime(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.logintime_ = value;
}

// uint64 notify_groupid = 8;
inline void user_device_info_notify::clear_notify_groupid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.notify_groupid_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::uint64_t user_device_info_notify::notify_groupid() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify.notify_groupid)
  return _internal_notify_groupid();
}
inline void user_device_info_notify::set_notify_groupid(::uint64_t value) {
  _internal_set_notify_groupid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify.notify_groupid)
}
inline ::uint64_t user_device_info_notify::_internal_notify_groupid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.notify_groupid_;
}
inline void user_device_info_notify::_internal_set_notify_groupid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.notify_groupid_ = value;
}

// -------------------------------------------------------------------

// user_device_info_notify_ack

// uint32 code = 1;
inline void user_device_info_notify_ack::clear_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t user_device_info_notify_ack::code() const {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify_ack.code)
  return _internal_code();
}
inline void user_device_info_notify_ack::set_code(::uint32_t value) {
  _internal_set_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:server.user_device_info_notify_ack.code)
}
inline ::uint32_t user_device_info_notify_ack::_internal_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.code_;
}
inline void user_device_info_notify_ack::_internal_set_code(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.code_ = value;
}

// string codeMsg = 2;
inline void user_device_info_notify_ack::clear_codemsg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.codemsg_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& user_device_info_notify_ack::codemsg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:server.user_device_info_notify_ack.codeMsg)
  return _internal_codemsg();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void user_device_info_notify_ack::set_codemsg(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.codemsg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:server.user_device_info_notify_ack.codeMsg)
}
inline ::std::string* PROTOBUF_NONNULL user_device_info_notify_ack::mutable_codemsg()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_codemsg();
  // @@protoc_insertion_point(field_mutable:server.user_device_info_notify_ack.codeMsg)
  return _s;
}
inline const ::std::string& user_device_info_notify_ack::_internal_codemsg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.codemsg_.Get();
}
inline void user_device_info_notify_ack::_internal_set_codemsg(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.codemsg_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL user_device_info_notify_ack::_internal_mutable_codemsg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.codemsg_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE user_device_info_notify_ack::release_codemsg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:server.user_device_info_notify_ack.codeMsg)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.codemsg_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.codemsg_.Set("", GetArena());
  }
  return released;
}
inline void user_device_info_notify_ack::set_allocated_codemsg(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.codemsg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.codemsg_.IsDefault()) {
    _impl_.codemsg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:server.user_device_info_notify_ack.codeMsg)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace server


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // user_5fbasic_2eproto_2epb_2eh
