CollectServer			/CollectServer/src              /plugins/CollectServer      
LogQueue				/LogQueue/src              		/plugins/LogQueue      
UserServer				/UserServer/src              	/plugins/UserServer    
ApiServer				/ApiServer/src              	/plugins/ApiServer    
SessionServer			/SessionServer/src          /plugins/SessionServer    
