Center 			/Center/src               /plugins/Center
Hello 			/Hello/src               /plugins/Hello
Interface           /Interface/src             	  /plugins/Interface
Logic           /Logic/src             	  /plugins/Logic
