all:
	#libpq.so 是gpdb编译的 ,libpqxx.a 是pqxx编译的
	g++ test1.cpp -o test1 -I.. -L../../../lib -lpqxx -lpq -std=c++11
	g++ test2.cpp -o test2 -I.. -L../../../lib -lpqxx -lpq -std=c++11
	g++ test3.cpp -o test3 -I.. -L../../../lib -lpqxx -lpq -std=c++11
	g++ test4.cpp -o test4 -I.. -L../../../lib -lpqxx -lpq -std=c++11
	g++ test5.cpp -o test5 -I.. -L../../../lib -lpqxx -lpq -std=c++11
	