---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-thunder-etcd-0
spec:
  accessModes: [ReadWriteOnce]
  capacity: {storage: 1Gi}
  hostPath:
    path: /data/thunder/etcd0
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-thunder-etcd-1
spec:
  accessModes: [ReadWriteOnce]
  capacity: {storage: 1Gi}
  hostPath:
    path: /data/thunder/etcd1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-thunder-etcd-2
spec:
  accessModes: [ReadWriteOnce]
  capacity: {storage: 1Gi}
  hostPath:
    path: /data/thunder/etcd2
  persistentVolumeReclaimPolicy: Retain
