apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunder-hello
  namespace: thunder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thunder-hello
  template:
    metadata:
      labels:
        app: thunder-hello
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: app
        image: thunder-hello-http:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_VERSION
          value: "v1"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: 27006
        - containerPort: 27007
