apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunder-hello-https
  namespace: thunder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thunder-hello-https
  template:
    metadata:
      labels:
        app: thunder-hello-https
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: nfs-plugins
        persistentVolumeClaim:
          claimName: thunder-plugins
      containers:
      - name: app
        image: thunder-hello-https:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_VERSION
          value: "v1"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: ETCD_ENDPOINT
          value: "http://thunder-etcd.thunder:2379"
        ports:
        - containerPort: 27443
        - containerPort: 27444
        volumeMounts:
        - name: nfs-plugins
          mountPath: /app/plugins
          subPath: HelloHttps
