apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunder-logic
  namespace: thunder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thunder-logic
      version: v1
  template:
    metadata:
      labels:
        app: thunder-logic
        version: v1
    spec:
      containers:
      - name: app
        image: thunder-logic:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_VERSION
          value: "v1"
        - name: INNER_PORT
          value: "16068"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ETCD_ENDPOINT
          value: "http://thunder-etcd.thunder:2379"
        ports:
        - containerPort: 16068
