apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunder-logic-v2
  namespace: thunder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thunder-logic
      version: v2
  template:
    metadata:
      labels:
        app: thunder-logic
        version: v2
    spec:
      volumes:
      - name: nfs-plugins
        persistentVolumeClaim:
          claimName: thunder-plugins
      containers:
      - name: app
        image: thunder-logic-v2:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_VERSION
          value: "v2"
        - name: INNER_PORT
          value: "16069"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ETCD_ENDPOINT
          value: "http://thunder-etcd.thunder:2379"
        ports:
        - containerPort: 16069
        volumeMounts:
        - name: nfs-plugins
          mountPath: /app/plugins
          subPath: Logic
