apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: thunder-logic
  namespace: thunder
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: thunder-logic
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
