<<<<<<< HEAD
 Hello 	   	   /Hello/plugins/Hello/          			/plugins/Hello
=======
 Hello 	   	   /Hello/plugins/Hello/          			/plugins/Hello
>>>>>>> branch 'master' of https://gitee.com/chenjiayi/thunder.git
