Center 		   	   /Center/plugins/Center/          			/plugins/Center
DataProxy    	   /DataProxy/plugins/Proxy/          			/plugins/DataProxy  
DbAgentR		   /DbAgentR/plugins/Agent/          			/plugins/DbAgent
DbAgentW	   	   /DbAgentW/plugins/Agent/          			/plugins/DbAgent
Collect 	       /Collect/plugins/collect/          			/plugins/Collect
LogQueue 	       /LogQueue/plugins/LogQueue/          		/plugins/LogQueue
Hello 	   	   	   /Hello/plugins/Hello/          				/plugins/Hello
User 	   	   	   /User/plugins/User/          			    /plugins/User
Api 	   	   	   /Api/plugins/Api/          			    	/plugins/Api
Session 	   	   /Session/plugins/Session/          			/plugins/Session
PgAgent		       /PgAgent/plugins/Agent/          			/plugins/PgAgent
