Interface 	   	   /Interface/plugins/          			/plugins/Interface
Hello 	   /Hello/plugins/          	    /plugins/Hello
Center               /Center/plugins/          			/plugins/Center
Logic               /Logic/plugins/          			/plugins/Logic
