syntax = "proto3";
package behaviour;

message attribute
{
	string n = 1;
	string v = 2;
}

message trace
{
	string appkey = 1;
	string type = 2;

	string user_id = 3;
	string device_id = 4;
	string platform = 5;

	string event_id = 6;
	string ip = 7;
	string location = 8;
	string session_id = 9;

	string app_version = 10;
	string channel = 11;
	string net = 12;
	string carrier = 13;
	string os = 14;
	string os_version = 15;

	string browser_brand = 16;
	string browser_version = 17;
	string referer_domain = 18;
	string url = 19;
	string ref = 20;
	string utm_source = 21;
	string utm_medium = 22;
	string utm_term = 23;
	string utm_campaign = 24;
	string utm_content = 25;

	repeated attribute attributes = 26;

	uint64 time = 27;
}

message device
{
	string appkey = 1;
	string type = 2;

	string user_id = 3;
	string device_id = 4;
	string platform = 5;

	string brand = 6;
	string model = 7;
	string imei = 8;
	string screen = 9;

	uint64 time = 10;
}


message user
{
	string appkey = 1;
	string type= 2;

	string user_id= 3;
	string device_id= 4;
	string platform= 5;

	repeated attribute attributes= 6;

	uint64 time= 7;

	uint32 gmid = 8;//后台给用户分配的ID
}

message behaviour
{
	repeated trace t = 1;
	repeated device d = 2;
	repeated user u = 3;

	string appkey = 4;
	string type= 5;

	string user_id = 6;
	string device_id= 7;
	string platform= 8;

	uint32 app_id =9;

	string log_info = 10;
	uint32 log_cmd = 11;

	uint64 time= 12;

	string date = 13;//时间聚合使用
	uint32 gmid = 14;//后台给用户分配的ID信息
}

message behaviour_ack
{
    int32 code           = 1;
    string msg          = 2;
    string warn 			= 3;
}


//获得gmid相关信息
message get_gmid_info
{
	uint32 app_id =1;	
	string device_id = 2;
	string user_id= 3;

	string utm_source = 4;
	string utm_medium= 5;

	string utm_term = 6;
	string utm_campaign= 7;
}

//获取gmid相关信息响应
message get_gmid_info_ack
{
	int32 code           = 1;
	string msg          = 2;
	int32 gmid 			= 3; //gmid
	string user_id          = 4;//用户的UserID
	
	string utm_source = 5;//广告来源	
	string utm_medium= 6;//广告媒介

	string utm_term = 7;//广告关键字
	string utm_campaign= 8;//广告名称
}


