syntax = "proto3";
package server;

/*
enum E_PROHIBIT
{
	BAN_NO								= 0;	///< 没有禁止
	BAN_TALK							= 1;	///< 禁言
	BAN_COMMUNITY						= 2;	///< 禁止你我圈发说说、评论、回复、点赞
	BAN_CREATE_GROUP					= 4;	///< 禁止创建群
	BAN_ATENTION						= 8;	///< 禁止关注
	BAN_LOGIN							= 16;	///< 禁止登录
}
*/

/*
message user_basic
{
	bytes session_key		   = 1; ///< 通过(临时客户端公钥与服务端私钥协商生成的)密钥加密的值.后续消息的加密key
	
	uint64 session_id	       = 3; ///< 会话id
	int32 start_seq			   = 4; ///< 客户端后续消息的起始seq
	uint64 user_id			   = 5;	///< 用户ID
	string dev_id              = 6; ///< 设备id
	uint32 user_type     	   = 7; ///< 用户类型
	uint32 client_type   	   = 8;///< 客户登录客户端类型 0:未定义1:安卓2 安卓平板 3:IOS 4:IPAD 5:网页 ,最初是推送第三方类型
	string login_ip			   = 9;///< 客户端IP地址
    uint64 user_identity	   = 10;///< 用户身份
    uint32 prohibit            = 11;///< 禁止
	uint32 platform_type	   = 12;///< 客户登录客户端类型 0:未定义1:安卓 2:IOS 3:MAC 5:Windows
	
	string language	   		   = 13;///< 客户端语言版本，如en-US、zh-CN、default，匹配不上的，使用default的
	
	string extend			   = 14;///< 客户端拓展json数据
	
	string client_version	   = 15;///< 客户端版本
	string app_key	   		   = 16;///< app key
}
*/

//用户设备状态通知
message user_device_info_notify
{
	int64 userId = 1;//用户id（必须）
	string devid = 2;//设备id（必须）

	uint32 	status = 3;//在线状态（必须）
    uint64	ssidFreshTime = 4;//最后状态时间（必须）
    
    uint64  sessionId = 5;//会话id(上线状态必须)
    string accNodeIdentify = 6;//网关连接符(上线状态必须)
    uint32	loginTime = 7;//登录时间(上线状态必须)
    
    uint64	notify_groupid = 8;//通知群服务使用
};

message user_device_info_notify_ack
{
	uint32 code = 1;
	string codeMsg =2;
};

