// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oss_sys.proto

#include "oss_sys.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class ConnectWorkerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConnectWorker>
      _instance;
} _ConnectWorker_default_instance_;
class TargetWorkerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TargetWorker>
      _instance;
} _TargetWorker_default_instance_;
class LogLevelDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LogLevel>
      _instance;
} _LogLevel_default_instance_;
namespace protobuf_oss_5fsys_2eproto {
static void InitDefaultsConnectWorker() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ConnectWorker_default_instance_;
    new (ptr) ::ConnectWorker();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ConnectWorker::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ConnectWorker =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsConnectWorker}, {}};

static void InitDefaultsTargetWorker() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_TargetWorker_default_instance_;
    new (ptr) ::TargetWorker();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::TargetWorker::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_TargetWorker =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsTargetWorker}, {}};

static void InitDefaultsLogLevel() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_LogLevel_default_instance_;
    new (ptr) ::LogLevel();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::LogLevel::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LogLevel =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLogLevel}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ConnectWorker.base);
  ::google::protobuf::internal::InitSCC(&scc_info_TargetWorker.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LogLevel.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ConnectWorker, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ConnectWorker, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ConnectWorker, worker_index_),
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TargetWorker, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TargetWorker, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TargetWorker, err_no_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TargetWorker, worker_identify_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TargetWorker, node_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::TargetWorker, err_msg_),
  3,
  0,
  1,
  2,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LogLevel, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LogLevel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::LogLevel, log_level_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::ConnectWorker)},
  { 7, 16, sizeof(::TargetWorker)},
  { 20, 26, sizeof(::LogLevel)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ConnectWorker_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_TargetWorker_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_LogLevel_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "oss_sys.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\ross_sys.proto\"%\n\rConnectWorker\022\024\n\014work"
      "er_index\030\001 \002(\005\"[\n\014TargetWorker\022\016\n\006err_no"
      "\030\001 \002(\005\022\027\n\017worker_identify\030\002 \002(\t\022\021\n\tnode_"
      "type\030\003 \002(\t\022\017\n\007err_msg\030\004 \001(\t\"\035\n\010LogLevel\022"
      "\021\n\tlog_level\030\001 \002(\005"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 178);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "oss_sys.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_oss_5fsys_2eproto

// ===================================================================

void ConnectWorker::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConnectWorker::kWorkerIndexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConnectWorker::ConnectWorker()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_oss_5fsys_2eproto::scc_info_ConnectWorker.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ConnectWorker)
}
ConnectWorker::ConnectWorker(const ConnectWorker& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  worker_index_ = from.worker_index_;
  // @@protoc_insertion_point(copy_constructor:ConnectWorker)
}

void ConnectWorker::SharedCtor() {
  worker_index_ = 0;
}

ConnectWorker::~ConnectWorker() {
  // @@protoc_insertion_point(destructor:ConnectWorker)
  SharedDtor();
}

void ConnectWorker::SharedDtor() {
}

void ConnectWorker::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ConnectWorker::descriptor() {
  ::protobuf_oss_5fsys_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oss_5fsys_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConnectWorker& ConnectWorker::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_oss_5fsys_2eproto::scc_info_ConnectWorker.base);
  return *internal_default_instance();
}


void ConnectWorker::Clear() {
// @@protoc_insertion_point(message_clear_start:ConnectWorker)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  worker_index_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ConnectWorker::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ConnectWorker)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 worker_index = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_worker_index();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &worker_index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ConnectWorker)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ConnectWorker)
  return false;
#undef DO_
}

void ConnectWorker::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ConnectWorker)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 worker_index = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->worker_index(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ConnectWorker)
}

::google::protobuf::uint8* ConnectWorker::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ConnectWorker)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 worker_index = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->worker_index(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ConnectWorker)
  return target;
}

size_t ConnectWorker::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ConnectWorker)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required int32 worker_index = 1;
  if (has_worker_index()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->worker_index());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConnectWorker::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ConnectWorker)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectWorker* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConnectWorker>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ConnectWorker)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ConnectWorker)
    MergeFrom(*source);
  }
}

void ConnectWorker::MergeFrom(const ConnectWorker& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ConnectWorker)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_worker_index()) {
    set_worker_index(from.worker_index());
  }
}

void ConnectWorker::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ConnectWorker)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectWorker::CopyFrom(const ConnectWorker& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ConnectWorker)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectWorker::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void ConnectWorker::Swap(ConnectWorker* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConnectWorker::InternalSwap(ConnectWorker* other) {
  using std::swap;
  swap(worker_index_, other->worker_index_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ConnectWorker::GetMetadata() const {
  protobuf_oss_5fsys_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oss_5fsys_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void TargetWorker::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TargetWorker::kErrNoFieldNumber;
const int TargetWorker::kWorkerIdentifyFieldNumber;
const int TargetWorker::kNodeTypeFieldNumber;
const int TargetWorker::kErrMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TargetWorker::TargetWorker()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_oss_5fsys_2eproto::scc_info_TargetWorker.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:TargetWorker)
}
TargetWorker::TargetWorker(const TargetWorker& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  worker_identify_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_worker_identify()) {
    worker_identify_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.worker_identify_);
  }
  node_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_node_type()) {
    node_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.node_type_);
  }
  err_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_err_msg()) {
    err_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.err_msg_);
  }
  err_no_ = from.err_no_;
  // @@protoc_insertion_point(copy_constructor:TargetWorker)
}

void TargetWorker::SharedCtor() {
  worker_identify_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  node_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  err_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  err_no_ = 0;
}

TargetWorker::~TargetWorker() {
  // @@protoc_insertion_point(destructor:TargetWorker)
  SharedDtor();
}

void TargetWorker::SharedDtor() {
  worker_identify_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  node_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  err_msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void TargetWorker::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* TargetWorker::descriptor() {
  ::protobuf_oss_5fsys_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oss_5fsys_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TargetWorker& TargetWorker::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_oss_5fsys_2eproto::scc_info_TargetWorker.base);
  return *internal_default_instance();
}


void TargetWorker::Clear() {
// @@protoc_insertion_point(message_clear_start:TargetWorker)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      worker_identify_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      node_type_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      err_msg_.ClearNonDefaultToEmptyNoArena();
    }
  }
  err_no_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool TargetWorker::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:TargetWorker)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 err_no = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_err_no();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &err_no_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string worker_identify = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_worker_identify()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->worker_identify().data(), static_cast<int>(this->worker_identify().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "TargetWorker.worker_identify");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string node_type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_node_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->node_type().data(), static_cast<int>(this->node_type().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "TargetWorker.node_type");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string err_msg = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_err_msg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->err_msg().data(), static_cast<int>(this->err_msg().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "TargetWorker.err_msg");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:TargetWorker)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:TargetWorker)
  return false;
#undef DO_
}

void TargetWorker::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:TargetWorker)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 err_no = 1;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->err_no(), output);
  }

  // required string worker_identify = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->worker_identify().data(), static_cast<int>(this->worker_identify().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "TargetWorker.worker_identify");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->worker_identify(), output);
  }

  // required string node_type = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->node_type().data(), static_cast<int>(this->node_type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "TargetWorker.node_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->node_type(), output);
  }

  // optional string err_msg = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->err_msg().data(), static_cast<int>(this->err_msg().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "TargetWorker.err_msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->err_msg(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:TargetWorker)
}

::google::protobuf::uint8* TargetWorker::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:TargetWorker)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 err_no = 1;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->err_no(), target);
  }

  // required string worker_identify = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->worker_identify().data(), static_cast<int>(this->worker_identify().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "TargetWorker.worker_identify");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->worker_identify(), target);
  }

  // required string node_type = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->node_type().data(), static_cast<int>(this->node_type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "TargetWorker.node_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->node_type(), target);
  }

  // optional string err_msg = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->err_msg().data(), static_cast<int>(this->err_msg().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "TargetWorker.err_msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->err_msg(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TargetWorker)
  return target;
}

size_t TargetWorker::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:TargetWorker)
  size_t total_size = 0;

  if (has_worker_identify()) {
    // required string worker_identify = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->worker_identify());
  }

  if (has_node_type()) {
    // required string node_type = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->node_type());
  }

  if (has_err_no()) {
    // required int32 err_no = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->err_no());
  }

  return total_size;
}
size_t TargetWorker::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TargetWorker)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000000b) ^ 0x0000000b) == 0) {  // All required fields are present.
    // required string worker_identify = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->worker_identify());

    // required string node_type = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->node_type());

    // required int32 err_no = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->err_no());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional string err_msg = 4;
  if (has_err_msg()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->err_msg());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TargetWorker::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TargetWorker)
  GOOGLE_DCHECK_NE(&from, this);
  const TargetWorker* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TargetWorker>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TargetWorker)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TargetWorker)
    MergeFrom(*source);
  }
}

void TargetWorker::MergeFrom(const TargetWorker& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TargetWorker)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_worker_identify();
      worker_identify_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.worker_identify_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_node_type();
      node_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.node_type_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_err_msg();
      err_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.err_msg_);
    }
    if (cached_has_bits & 0x00000008u) {
      err_no_ = from.err_no_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void TargetWorker::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TargetWorker)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TargetWorker::CopyFrom(const TargetWorker& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TargetWorker)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TargetWorker::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000b) != 0x0000000b) return false;
  return true;
}

void TargetWorker::Swap(TargetWorker* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TargetWorker::InternalSwap(TargetWorker* other) {
  using std::swap;
  worker_identify_.Swap(&other->worker_identify_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  node_type_.Swap(&other->node_type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  err_msg_.Swap(&other->err_msg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(err_no_, other->err_no_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata TargetWorker::GetMetadata() const {
  protobuf_oss_5fsys_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oss_5fsys_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LogLevel::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LogLevel::kLogLevelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LogLevel::LogLevel()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_oss_5fsys_2eproto::scc_info_LogLevel.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:LogLevel)
}
LogLevel::LogLevel(const LogLevel& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  log_level_ = from.log_level_;
  // @@protoc_insertion_point(copy_constructor:LogLevel)
}

void LogLevel::SharedCtor() {
  log_level_ = 0;
}

LogLevel::~LogLevel() {
  // @@protoc_insertion_point(destructor:LogLevel)
  SharedDtor();
}

void LogLevel::SharedDtor() {
}

void LogLevel::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LogLevel::descriptor() {
  ::protobuf_oss_5fsys_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oss_5fsys_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LogLevel& LogLevel::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_oss_5fsys_2eproto::scc_info_LogLevel.base);
  return *internal_default_instance();
}


void LogLevel::Clear() {
// @@protoc_insertion_point(message_clear_start:LogLevel)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  log_level_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool LogLevel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LogLevel)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 log_level = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_log_level();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &log_level_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LogLevel)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LogLevel)
  return false;
#undef DO_
}

void LogLevel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LogLevel)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 log_level = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->log_level(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:LogLevel)
}

::google::protobuf::uint8* LogLevel::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:LogLevel)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 log_level = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->log_level(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LogLevel)
  return target;
}

size_t LogLevel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LogLevel)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required int32 log_level = 1;
  if (has_log_level()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->log_level());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LogLevel::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LogLevel)
  GOOGLE_DCHECK_NE(&from, this);
  const LogLevel* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LogLevel>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LogLevel)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LogLevel)
    MergeFrom(*source);
  }
}

void LogLevel::MergeFrom(const LogLevel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LogLevel)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_log_level()) {
    set_log_level(from.log_level());
  }
}

void LogLevel::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LogLevel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LogLevel::CopyFrom(const LogLevel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LogLevel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogLevel::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void LogLevel::Swap(LogLevel* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LogLevel::InternalSwap(LogLevel* other) {
  using std::swap;
  swap(log_level_, other->log_level_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LogLevel::GetMetadata() const {
  protobuf_oss_5fsys_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_oss_5fsys_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ConnectWorker* Arena::CreateMaybeMessage< ::ConnectWorker >(Arena* arena) {
  return Arena::CreateInternal< ::ConnectWorker >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::TargetWorker* Arena::CreateMaybeMessage< ::TargetWorker >(Arena* arena) {
  return Arena::CreateInternal< ::TargetWorker >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::LogLevel* Arena::CreateMaybeMessage< ::LogLevel >(Arena* arena) {
  return Arena::CreateInternal< ::LogLevel >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
