CenterServer 			/CenterServer/src             	/plugins/CenterServer 
DataProxyServer 		/DataProxyServer/src            /plugins/DataProxyServer   
DbAgentServer 			/DbAgentServer/src          	/plugins/DbAgentServer   
HelloServer 			/HelloServer/src             	/plugins/HelloServer
PgAgentServer 			/PgAgentServer/src          	/plugins/PgAgentServer   
