Center 			/Center/src               /plugins/Center 
DataProxy 		/DataProxy/src            /plugins/DataProxy   
DbAgent 		/DbAgent/src          	  /plugins/DbAgent   
Hello 			/Hello/src             	  /plugins/Hello
PgAgent 		/PgAgent/src          	  /plugins/PgAgent   
LogQueue		/LogQueue/src             /plugins/LogQueue   
