// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: http.proto
// Protobuf C++ Version: 7.35.0-dev

#ifndef http_2eproto_2epb_2eh
#define http_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_http_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_http_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_http_2eproto;
}  // extern "C"
class HttpMsg;
struct HttpMsgGlobalsTypeInternal;
extern HttpMsgGlobalsTypeInternal _HttpMsg_globals_;
extern const ::google::protobuf::internal::ClassDataFull HttpMsg_class_data_;
class HttpMsg_Header;
struct HttpMsg_HeaderGlobalsTypeInternal;
extern HttpMsg_HeaderGlobalsTypeInternal _HttpMsg_Header_globals_;
extern const ::google::protobuf::internal::ClassDataFull HttpMsg_Header_class_data_;
class HttpMsg_HeadersEntry_DoNotUse;
struct HttpMsg_HeadersEntry_DoNotUseGlobalsTypeInternal;
extern HttpMsg_HeadersEntry_DoNotUseGlobalsTypeInternal _HttpMsg_HeadersEntry_DoNotUse_globals_;
extern const ::google::protobuf::internal::ClassDataFull HttpMsg_HeadersEntry_DoNotUse_class_data_;
class HttpMsg_ParamsEntry_DoNotUse;
struct HttpMsg_ParamsEntry_DoNotUseGlobalsTypeInternal;
extern HttpMsg_ParamsEntry_DoNotUseGlobalsTypeInternal _HttpMsg_ParamsEntry_DoNotUse_globals_;
extern const ::google::protobuf::internal::ClassDataFull HttpMsg_ParamsEntry_DoNotUse_class_data_;
class HttpMsg_Upgrade;
struct HttpMsg_UpgradeGlobalsTypeInternal;
extern HttpMsg_UpgradeGlobalsTypeInternal _HttpMsg_Upgrade_globals_;
extern const ::google::protobuf::internal::ClassDataFull HttpMsg_Upgrade_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED HttpMsg_Upgrade final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:HttpMsg.Upgrade) */ {
 public:
  inline HttpMsg_Upgrade() : HttpMsg_Upgrade(nullptr) {}
  ~HttpMsg_Upgrade() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HttpMsg_Upgrade* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HttpMsg_Upgrade));
  }
#endif

  template <typename = void>
  explicit constexpr HttpMsg_Upgrade(::google::protobuf::internal::ConstantInitialized);

  inline HttpMsg_Upgrade(const HttpMsg_Upgrade& from) : HttpMsg_Upgrade(nullptr, from) {}
  inline HttpMsg_Upgrade(HttpMsg_Upgrade&& from) noexcept
      : HttpMsg_Upgrade(nullptr, ::std::move(from)) {}
  inline HttpMsg_Upgrade& operator=(const HttpMsg_Upgrade& from) {
    CopyFrom(from);
    return *this;
  }
  inline HttpMsg_Upgrade& operator=(HttpMsg_Upgrade&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const HttpMsg_Upgrade& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::default_instance<HttpMsg_Upgrade>(
        &_HttpMsg_Upgrade_globals_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(HttpMsg_Upgrade& a, HttpMsg_Upgrade& b) { a.Swap(&b); }
  inline void Swap(HttpMsg_Upgrade* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HttpMsg_Upgrade* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] HttpMsg_Upgrade* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HttpMsg_Upgrade>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HttpMsg_Upgrade& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HttpMsg_Upgrade& from) { HttpMsg_Upgrade::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HttpMsg_Upgrade* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "HttpMsg.Upgrade"; }

  explicit HttpMsg_Upgrade(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HttpMsg_Upgrade(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HttpMsg_Upgrade& from);
  HttpMsg_Upgrade(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HttpMsg_Upgrade&& from) noexcept
      : HttpMsg_Upgrade(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kProtocolFieldNumber = 2,
    kIsUpgradeFieldNumber = 1,
  };
  // string protocol = 2;
  void clear_protocol() ;
  [[nodiscard]] const ::std::string& protocol() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_protocol(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_protocol();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_protocol();
  void set_allocated_protocol(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_protocol() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_protocol(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_protocol();

  public:
  // bool is_upgrade = 1;
  void clear_is_upgrade() ;
  [[nodiscard]] bool is_upgrade() const;
  void set_is_upgrade(bool value);

  private:
  bool _internal_is_upgrade() const;
  void _internal_set_is_upgrade(bool value);

  public:
  // @@protoc_insertion_point(class_scope:HttpMsg.Upgrade)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 32,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HttpMsg_Upgrade& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr protocol_;
    bool is_upgrade_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_http_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HttpMsg_Upgrade_class_data_;
// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED HttpMsg_ParamsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  HttpMsg_ParamsEntry_DoNotUse();
  template <typename = void>
  explicit constexpr HttpMsg_ParamsEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit HttpMsg_ParamsEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_message_globals() {
    return &_HttpMsg_ParamsEntry_DoNotUse_globals_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_http_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 36,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull HttpMsg_ParamsEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED HttpMsg_HeadersEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                             ::google::protobuf::internal::WireFormatLite::TYPE_STRING> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::std::string, ::std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING>;
  HttpMsg_HeadersEntry_DoNotUse();
  template <typename = void>
  explicit constexpr HttpMsg_HeadersEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit HttpMsg_HeadersEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_message_globals() {
    return &_HttpMsg_HeadersEntry_DoNotUse_globals_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_http_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 37,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull HttpMsg_HeadersEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED HttpMsg_Header final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:HttpMsg.Header) */ {
 public:
  inline HttpMsg_Header() : HttpMsg_Header(nullptr) {}
  ~HttpMsg_Header() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HttpMsg_Header* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HttpMsg_Header));
  }
#endif

  template <typename = void>
  explicit constexpr HttpMsg_Header(::google::protobuf::internal::ConstantInitialized);

  inline HttpMsg_Header(const HttpMsg_Header& from) : HttpMsg_Header(nullptr, from) {}
  inline HttpMsg_Header(HttpMsg_Header&& from) noexcept
      : HttpMsg_Header(nullptr, ::std::move(from)) {}
  inline HttpMsg_Header& operator=(const HttpMsg_Header& from) {
    CopyFrom(from);
    return *this;
  }
  inline HttpMsg_Header& operator=(HttpMsg_Header&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const HttpMsg_Header& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::default_instance<HttpMsg_Header>(
        &_HttpMsg_Header_globals_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(HttpMsg_Header& a, HttpMsg_Header& b) { a.Swap(&b); }
  inline void Swap(HttpMsg_Header* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HttpMsg_Header* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] HttpMsg_Header* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HttpMsg_Header>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HttpMsg_Header& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HttpMsg_Header& from) { HttpMsg_Header::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HttpMsg_Header* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "HttpMsg.Header"; }

  explicit HttpMsg_Header(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HttpMsg_Header(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HttpMsg_Header& from);
  HttpMsg_Header(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HttpMsg_Header&& from) noexcept
      : HttpMsg_Header(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kHeaderNameFieldNumber = 1,
    kHeaderValueFieldNumber = 2,
  };
  // string header_name = 1;
  void clear_header_name() ;
  [[nodiscard]] const ::std::string& header_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_header_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_header_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_header_name();
  void set_allocated_header_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_header_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_header_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_header_name();

  public:
  // bytes header_value = 2;
  void clear_header_value() ;
  [[nodiscard]] const ::std::string& header_value() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_header_value(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_header_value();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_header_value();
  void set_allocated_header_value(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_header_value() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_header_value(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_header_value();

  public:
  // @@protoc_insertion_point(class_scope:HttpMsg.Header)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HttpMsg_Header& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr header_name_;
    ::google::protobuf::internal::ArenaStringPtr header_value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_http_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HttpMsg_Header_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED HttpMsg final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:HttpMsg) */ {
 public:
  inline HttpMsg() : HttpMsg(nullptr) {}
  ~HttpMsg() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HttpMsg* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HttpMsg));
  }
#endif

  template <typename = void>
  explicit constexpr HttpMsg(::google::protobuf::internal::ConstantInitialized);

  inline HttpMsg(const HttpMsg& from) : HttpMsg(nullptr, from) {}
  inline HttpMsg(HttpMsg&& from) noexcept
      : HttpMsg(nullptr, ::std::move(from)) {}
  inline HttpMsg& operator=(const HttpMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline HttpMsg& operator=(HttpMsg&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const HttpMsg& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::default_instance<HttpMsg>(
        &_HttpMsg_globals_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(HttpMsg& a, HttpMsg& b) { a.Swap(&b); }
  inline void Swap(HttpMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HttpMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] HttpMsg* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HttpMsg>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HttpMsg& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HttpMsg& from) { HttpMsg::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HttpMsg* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "HttpMsg"; }

  explicit HttpMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HttpMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HttpMsg& from);
  HttpMsg(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HttpMsg&& from) noexcept
      : HttpMsg(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Header = HttpMsg_Header;
  using Upgrade = HttpMsg_Upgrade;

  // accessors -------------------------------------------------------
  enum : int {
    kUrlFieldNumber = 8,
    kBodyFieldNumber = 10,
    kPathFieldNumber = 14,
    kUpgradeFieldNumber = 16,
    kTypeFieldNumber = 1,
    kHttpMajorFieldNumber = 2,
    kHttpMinorFieldNumber = 3,
    kContentLengthFieldNumber = 4,
    kMethodFieldNumber = 5,
    kStatusCodeFieldNumber = 6,
    kEncodingFieldNumber = 7,
    kIsDecodingFieldNumber = 15,
    kKeepAliveFieldNumber = 17,
    kHeadersFieldNumber = 9,
    kParamsFieldNumber = 18,
  };
  // string url = 8;
  void clear_url() ;
  [[nodiscard]] const ::std::string& url() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_url(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_url();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_url();
  void set_allocated_url(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_url() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_url(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_url();

  public:
  // bytes body = 10;
  void clear_body() ;
  [[nodiscard]] const ::std::string& body() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_body(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_body();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_body();
  void set_allocated_body(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_body() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_body(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_body();

  public:
  // string path = 14;
  void clear_path() ;
  [[nodiscard]] const ::std::string& path() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_path(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_path();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_path();
  void set_allocated_path(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_path(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_path();

  public:
  // .HttpMsg.Upgrade upgrade = 16;
  [[nodiscard]] bool has_upgrade()
      const;
  void clear_upgrade() ;
  [[nodiscard]] const ::HttpMsg_Upgrade& upgrade() const;
  [[nodiscard]] ::HttpMsg_Upgrade* PROTOBUF_NULLABLE release_upgrade();
  ::HttpMsg_Upgrade* PROTOBUF_NONNULL mutable_upgrade();
  void set_allocated_upgrade(::HttpMsg_Upgrade* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_upgrade(::HttpMsg_Upgrade* PROTOBUF_NULLABLE value);
  ::HttpMsg_Upgrade* PROTOBUF_NULLABLE unsafe_arena_release_upgrade();

  private:
  const ::HttpMsg_Upgrade& _internal_upgrade() const;
  ::HttpMsg_Upgrade* PROTOBUF_NONNULL _internal_mutable_upgrade();

  public:
  // int32 type = 1;
  void clear_type() ;
  [[nodiscard]] ::int32_t type() const;
  void set_type(::int32_t value);

  private:
  ::int32_t _internal_type() const;
  void _internal_set_type(::int32_t value);

  public:
  // int32 http_major = 2;
  void clear_http_major() ;
  [[nodiscard]] ::int32_t http_major() const;
  void set_http_major(::int32_t value);

  private:
  ::int32_t _internal_http_major() const;
  void _internal_set_http_major(::int32_t value);

  public:
  // int32 http_minor = 3;
  void clear_http_minor() ;
  [[nodiscard]] ::int32_t http_minor() const;
  void set_http_minor(::int32_t value);

  private:
  ::int32_t _internal_http_minor() const;
  void _internal_set_http_minor(::int32_t value);

  public:
  // int32 content_length = 4;
  void clear_content_length() ;
  [[nodiscard]] ::int32_t content_length() const;
  void set_content_length(::int32_t value);

  private:
  ::int32_t _internal_content_length() const;
  void _internal_set_content_length(::int32_t value);

  public:
  // int32 method = 5;
  void clear_method() ;
  [[nodiscard]] ::int32_t method() const;
  void set_method(::int32_t value);

  private:
  ::int32_t _internal_method() const;
  void _internal_set_method(::int32_t value);

  public:
  // int32 status_code = 6;
  void clear_status_code() ;
  [[nodiscard]] ::int32_t status_code() const;
  void set_status_code(::int32_t value);

  private:
  ::int32_t _internal_status_code() const;
  void _internal_set_status_code(::int32_t value);

  public:
  // int32 encoding = 7;
  void clear_encoding() ;
  [[nodiscard]] ::int32_t encoding() const;
  void set_encoding(::int32_t value);

  private:
  ::int32_t _internal_encoding() const;
  void _internal_set_encoding(::int32_t value);

  public:
  // bool is_decoding = 15;
  void clear_is_decoding() ;
  [[nodiscard]] bool is_decoding() const;
  void set_is_decoding(bool value);

  private:
  bool _internal_is_decoding() const;
  void _internal_set_is_decoding(bool value);

  public:
  // float keep_alive = 17;
  void clear_keep_alive() ;
  [[nodiscard]] float keep_alive() const;
  void set_keep_alive(float value);

  private:
  float _internal_keep_alive() const;
  void _internal_set_keep_alive(float value);

  public:
  // map<string, string> headers = 9;
  [[nodiscard]] int headers_size()
      const;
  private:
  int _internal_headers_size() const;

  public:
  void clear_headers() ;
  [[nodiscard]] const ::google::protobuf::Map<::std::string, ::std::string>& headers() const;
  [[nodiscard]] ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_headers();

  private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_headers() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_headers();

  public:
  // map<string, string> params = 18;
  [[nodiscard]] int params_size()
      const;
  private:
  int _internal_params_size() const;

  public:
  void clear_params() ;
  [[nodiscard]] const ::google::protobuf::Map<::std::string, ::std::string>& params() const;
  [[nodiscard]] ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL mutable_params();

  private:
  const ::google::protobuf::Map<::std::string, ::std::string>& _internal_params() const;
  ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL _internal_mutable_params();

  public:
  // @@protoc_insertion_point(class_scope:HttpMsg)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 15,
                                   3, 44,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HttpMsg& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr url_;
    ::google::protobuf::internal::ArenaStringPtr body_;
    ::google::protobuf::internal::ArenaStringPtr path_;
    ::HttpMsg_Upgrade* PROTOBUF_NULLABLE upgrade_;
    ::int32_t type_;
    ::int32_t http_major_;
    ::int32_t http_minor_;
    ::int32_t content_length_;
    ::int32_t method_;
    ::int32_t status_code_;
    ::int32_t encoding_;
    bool is_decoding_;
    float keep_alive_;
    ::google::protobuf::internal::MapField<HttpMsg_HeadersEntry_DoNotUse, ::std::string, ::std::string> headers_;
    ::google::protobuf::internal::MapField<HttpMsg_ParamsEntry_DoNotUse, ::std::string, ::std::string> params_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_http_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HttpMsg_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// HttpMsg_Header

// string header_name = 1;
inline void HttpMsg_Header::clear_header_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.header_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& HttpMsg_Header::header_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:HttpMsg.Header.header_name)
  return _internal_header_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HttpMsg_Header::set_header_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.header_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:HttpMsg.Header.header_name)
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg_Header::mutable_header_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_header_name();
  // @@protoc_insertion_point(field_mutable:HttpMsg.Header.header_name)
  return _s;
}
inline const ::std::string& HttpMsg_Header::_internal_header_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.header_name_.Get();
}
inline void HttpMsg_Header::_internal_set_header_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.header_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg_Header::_internal_mutable_header_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.header_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HttpMsg_Header::release_header_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:HttpMsg.Header.header_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.header_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.header_name_.Set("", GetArena());
  }
  return released;
}
inline void HttpMsg_Header::set_allocated_header_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.header_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.header_name_.IsDefault()) {
    _impl_.header_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Header.header_name)
}

// bytes header_value = 2;
inline void HttpMsg_Header::clear_header_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.header_value_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& HttpMsg_Header::header_value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:HttpMsg.Header.header_value)
  return _internal_header_value();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HttpMsg_Header::set_header_value(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.header_value_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:HttpMsg.Header.header_value)
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg_Header::mutable_header_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_header_value();
  // @@protoc_insertion_point(field_mutable:HttpMsg.Header.header_value)
  return _s;
}
inline const ::std::string& HttpMsg_Header::_internal_header_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.header_value_.Get();
}
inline void HttpMsg_Header::_internal_set_header_value(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.header_value_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg_Header::_internal_mutable_header_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.header_value_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HttpMsg_Header::release_header_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:HttpMsg.Header.header_value)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.header_value_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.header_value_.Set("", GetArena());
  }
  return released;
}
inline void HttpMsg_Header::set_allocated_header_value(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.header_value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.header_value_.IsDefault()) {
    _impl_.header_value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Header.header_value)
}

// -------------------------------------------------------------------

// HttpMsg_Upgrade

// bool is_upgrade = 1;
inline void HttpMsg_Upgrade::clear_is_upgrade() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_upgrade_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool HttpMsg_Upgrade::is_upgrade() const {
  // @@protoc_insertion_point(field_get:HttpMsg.Upgrade.is_upgrade)
  return _internal_is_upgrade();
}
inline void HttpMsg_Upgrade::set_is_upgrade(bool value) {
  _internal_set_is_upgrade(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:HttpMsg.Upgrade.is_upgrade)
}
inline bool HttpMsg_Upgrade::_internal_is_upgrade() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_upgrade_;
}
inline void HttpMsg_Upgrade::_internal_set_is_upgrade(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_upgrade_ = value;
}

// string protocol = 2;
inline void HttpMsg_Upgrade::clear_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.protocol_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& HttpMsg_Upgrade::protocol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:HttpMsg.Upgrade.protocol)
  return _internal_protocol();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HttpMsg_Upgrade::set_protocol(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.protocol_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:HttpMsg.Upgrade.protocol)
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg_Upgrade::mutable_protocol()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_protocol();
  // @@protoc_insertion_point(field_mutable:HttpMsg.Upgrade.protocol)
  return _s;
}
inline const ::std::string& HttpMsg_Upgrade::_internal_protocol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.protocol_.Get();
}
inline void HttpMsg_Upgrade::_internal_set_protocol(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.protocol_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg_Upgrade::_internal_mutable_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.protocol_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HttpMsg_Upgrade::release_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:HttpMsg.Upgrade.protocol)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.protocol_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.protocol_.Set("", GetArena());
  }
  return released;
}
inline void HttpMsg_Upgrade::set_allocated_protocol(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.protocol_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.protocol_.IsDefault()) {
    _impl_.protocol_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Upgrade.protocol)
}

// -------------------------------------------------------------------

// HttpMsg

// int32 type = 1;
inline void HttpMsg::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t HttpMsg::type() const {
  // @@protoc_insertion_point(field_get:HttpMsg.type)
  return _internal_type();
}
inline void HttpMsg::set_type(::int32_t value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:HttpMsg.type)
}
inline ::int32_t HttpMsg::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_;
}
inline void HttpMsg::_internal_set_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// int32 http_major = 2;
inline void HttpMsg::clear_http_major() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.http_major_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t HttpMsg::http_major() const {
  // @@protoc_insertion_point(field_get:HttpMsg.http_major)
  return _internal_http_major();
}
inline void HttpMsg::set_http_major(::int32_t value) {
  _internal_set_http_major(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:HttpMsg.http_major)
}
inline ::int32_t HttpMsg::_internal_http_major() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.http_major_;
}
inline void HttpMsg::_internal_set_http_major(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.http_major_ = value;
}

// int32 http_minor = 3;
inline void HttpMsg::clear_http_minor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.http_minor_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t HttpMsg::http_minor() const {
  // @@protoc_insertion_point(field_get:HttpMsg.http_minor)
  return _internal_http_minor();
}
inline void HttpMsg::set_http_minor(::int32_t value) {
  _internal_set_http_minor(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:HttpMsg.http_minor)
}
inline ::int32_t HttpMsg::_internal_http_minor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.http_minor_;
}
inline void HttpMsg::_internal_set_http_minor(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.http_minor_ = value;
}

// int32 content_length = 4;
inline void HttpMsg::clear_content_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_length_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::int32_t HttpMsg::content_length() const {
  // @@protoc_insertion_point(field_get:HttpMsg.content_length)
  return _internal_content_length();
}
inline void HttpMsg::set_content_length(::int32_t value) {
  _internal_set_content_length(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:HttpMsg.content_length)
}
inline ::int32_t HttpMsg::_internal_content_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.content_length_;
}
inline void HttpMsg::_internal_set_content_length(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_length_ = value;
}

// int32 method = 5;
inline void HttpMsg::clear_method() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::int32_t HttpMsg::method() const {
  // @@protoc_insertion_point(field_get:HttpMsg.method)
  return _internal_method();
}
inline void HttpMsg::set_method(::int32_t value) {
  _internal_set_method(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:HttpMsg.method)
}
inline ::int32_t HttpMsg::_internal_method() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.method_;
}
inline void HttpMsg::_internal_set_method(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.method_ = value;
}

// int32 status_code = 6;
inline void HttpMsg::clear_status_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_code_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::int32_t HttpMsg::status_code() const {
  // @@protoc_insertion_point(field_get:HttpMsg.status_code)
  return _internal_status_code();
}
inline void HttpMsg::set_status_code(::int32_t value) {
  _internal_set_status_code(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:HttpMsg.status_code)
}
inline ::int32_t HttpMsg::_internal_status_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_code_;
}
inline void HttpMsg::_internal_set_status_code(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_code_ = value;
}

// int32 encoding = 7;
inline void HttpMsg::clear_encoding() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encoding_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::int32_t HttpMsg::encoding() const {
  // @@protoc_insertion_point(field_get:HttpMsg.encoding)
  return _internal_encoding();
}
inline void HttpMsg::set_encoding(::int32_t value) {
  _internal_set_encoding(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:HttpMsg.encoding)
}
inline ::int32_t HttpMsg::_internal_encoding() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.encoding_;
}
inline void HttpMsg::_internal_set_encoding(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.encoding_ = value;
}

// string url = 8;
inline void HttpMsg::clear_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.url_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& HttpMsg::url() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:HttpMsg.url)
  return _internal_url();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HttpMsg::set_url(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.url_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:HttpMsg.url)
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg::mutable_url()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:HttpMsg.url)
  return _s;
}
inline const ::std::string& HttpMsg::_internal_url() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.url_.Get();
}
inline void HttpMsg::_internal_set_url(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.url_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg::_internal_mutable_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.url_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HttpMsg::release_url() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:HttpMsg.url)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.url_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.url_.Set("", GetArena());
  }
  return released;
}
inline void HttpMsg::set_allocated_url(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.url_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.url)
}

// map<string, string> headers = 9;
inline int HttpMsg::_internal_headers_size() const {
  return _internal_headers().size();
}
inline int HttpMsg::headers_size() const {
  return _internal_headers_size();
}
inline void HttpMsg::clear_headers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.headers_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00002000U);
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& HttpMsg::_internal_headers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.headers_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& HttpMsg::headers() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:HttpMsg.headers)
  return _internal_headers();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL HttpMsg::_internal_mutable_headers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.headers_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL HttpMsg::mutable_headers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_mutable_map:HttpMsg.headers)
  return _internal_mutable_headers();
}

// bytes body = 10;
inline void HttpMsg::clear_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& HttpMsg::body() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:HttpMsg.body)
  return _internal_body();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HttpMsg::set_body(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.body_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:HttpMsg.body)
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg::mutable_body()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:HttpMsg.body)
  return _s;
}
inline const ::std::string& HttpMsg::_internal_body() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.body_.Get();
}
inline void HttpMsg::_internal_set_body(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg::_internal_mutable_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.body_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HttpMsg::release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:HttpMsg.body)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.body_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.body_.Set("", GetArena());
  }
  return released;
}
inline void HttpMsg::set_allocated_body(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.body_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.body_.IsDefault()) {
    _impl_.body_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.body)
}

// string path = 14;
inline void HttpMsg::clear_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& HttpMsg::path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:HttpMsg.path)
  return _internal_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void HttpMsg::set_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:HttpMsg.path)
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg::mutable_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:HttpMsg.path)
  return _s;
}
inline const ::std::string& HttpMsg::_internal_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_.Get();
}
inline void HttpMsg::_internal_set_path(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL HttpMsg::_internal_mutable_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.path_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE HttpMsg::release_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:HttpMsg.path)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.path_.Set("", GetArena());
  }
  return released;
}
inline void HttpMsg::set_allocated_path(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.path)
}

// bool is_decoding = 15;
inline void HttpMsg::clear_is_decoding() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_decoding_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline bool HttpMsg::is_decoding() const {
  // @@protoc_insertion_point(field_get:HttpMsg.is_decoding)
  return _internal_is_decoding();
}
inline void HttpMsg::set_is_decoding(bool value) {
  _internal_set_is_decoding(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:HttpMsg.is_decoding)
}
inline bool HttpMsg::_internal_is_decoding() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_decoding_;
}
inline void HttpMsg::_internal_set_is_decoding(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_decoding_ = value;
}

// .HttpMsg.Upgrade upgrade = 16;
inline bool HttpMsg::has_upgrade() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.upgrade_ != nullptr);
  return value;
}
inline void HttpMsg::clear_upgrade() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.upgrade_ != nullptr) _impl_.upgrade_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::HttpMsg_Upgrade& HttpMsg::_internal_upgrade() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::HttpMsg_Upgrade* p = _impl_.upgrade_;
  return p != nullptr ? *p : *::google::protobuf::internal::MessageGlobalsBase::default_instance<::HttpMsg_Upgrade>(&::_HttpMsg_Upgrade_globals_);
}
inline const ::HttpMsg_Upgrade& HttpMsg::upgrade() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:HttpMsg.upgrade)
  return _internal_upgrade();
}
inline void HttpMsg::unsafe_arena_set_allocated_upgrade(
    ::HttpMsg_Upgrade* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.upgrade_);
  }
  _impl_.upgrade_ = reinterpret_cast<::HttpMsg_Upgrade*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:HttpMsg.upgrade)
}
inline ::HttpMsg_Upgrade* PROTOBUF_NULLABLE HttpMsg::release_upgrade() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::HttpMsg_Upgrade* released = _impl_.upgrade_;
  _impl_.upgrade_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::HttpMsg_Upgrade* PROTOBUF_NULLABLE HttpMsg::unsafe_arena_release_upgrade() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:HttpMsg.upgrade)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::HttpMsg_Upgrade* temp = _impl_.upgrade_;
  _impl_.upgrade_ = nullptr;
  return temp;
}
inline ::HttpMsg_Upgrade* PROTOBUF_NONNULL HttpMsg::_internal_mutable_upgrade() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.upgrade_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::HttpMsg_Upgrade>(GetArena());
    _impl_.upgrade_ = reinterpret_cast<::HttpMsg_Upgrade*>(p);
  }
  return _impl_.upgrade_;
}
inline ::HttpMsg_Upgrade* PROTOBUF_NONNULL HttpMsg::mutable_upgrade()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::HttpMsg_Upgrade* _msg = _internal_mutable_upgrade();
  // @@protoc_insertion_point(field_mutable:HttpMsg.upgrade)
  return _msg;
}
inline void HttpMsg::set_allocated_upgrade(::HttpMsg_Upgrade* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.upgrade_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.upgrade_ = reinterpret_cast<::HttpMsg_Upgrade*>(value);
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.upgrade)
}

// float keep_alive = 17;
inline void HttpMsg::clear_keep_alive() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keep_alive_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline float HttpMsg::keep_alive() const {
  // @@protoc_insertion_point(field_get:HttpMsg.keep_alive)
  return _internal_keep_alive();
}
inline void HttpMsg::set_keep_alive(float value) {
  _internal_set_keep_alive(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:HttpMsg.keep_alive)
}
inline float HttpMsg::_internal_keep_alive() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.keep_alive_;
}
inline void HttpMsg::_internal_set_keep_alive(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keep_alive_ = value;
}

// map<string, string> params = 18;
inline int HttpMsg::_internal_params_size() const {
  return _internal_params().size();
}
inline int HttpMsg::params_size() const {
  return _internal_params_size();
}
inline void HttpMsg::clear_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.params_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00004000U);
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& HttpMsg::_internal_params() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.params_.GetMap();
}
inline const ::google::protobuf::Map<::std::string, ::std::string>& HttpMsg::params() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:HttpMsg.params)
  return _internal_params();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL HttpMsg::_internal_mutable_params() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.params_.MutableMap();
}
inline ::google::protobuf::Map<::std::string, ::std::string>* PROTOBUF_NONNULL HttpMsg::mutable_params()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_mutable_map:HttpMsg.params)
  return _internal_mutable_params();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // http_2eproto_2epb_2eh
