# 需要编译的节点可执行文件（复制 Hello 后改名）；与旧 server.dep 中 ORTHER_TARGETS 一致
ORTHER_TARGETS = Hello Logic Interface

$(info  $(ORTHER_TARGETS))
CC = gcc
CXX = g++
#编译选项 -DDISABLE_COROUTINUE
CFLAGS = -g -Og -Wno-error 
CPPFLAGS = -g -Og -D_GNU_SOURCE=1 -D_REENTRANT -fPIC -DNODE_BEAT=10.0 -DWORKER_OVERDUE=60.0 -std=c++20 -Wno-deprecated-declarations -Wno-pmf-conversions -Wno-error -Wno-error=format-security
#链接选项
CXXFLAG = -g -Og -Wall -ggdb -m64 -Wl,--export-dynamic 

DEFINE_SERVER =

ifeq ($(unit_test),y)
CPPFLAGS += -DUNIT_TEST
endif

ARCH:=$(shell uname -m)

ARCH32:=i686
ARCH64:=x86_64

ifeq ($(ARCH),$(ARCH64))
SYSTEM_LIB_PATH:=/usr/lib64
else
SYSTEM_LIB_PATH:=/usr/lib
endif
3PARTY_PATH = ../../3party
UTIL_PATH = ../../Util
# protobuf 35 依赖的 Abseil 静态库（与 3party/protobuf 构建一致；不修改 3party 仅引用路径）
ABSL_ARCHIVES := $(shell find $(3PARTY_PATH)/protobuf/build/_deps/absl-build -name 'libabsl*.a' 2>/dev/null)
ABSL_LINK := -Wl,--start-group $(ABSL_ARCHIVES) -Wl,--end-group

NET_PATH = ..

DEPLOY_BIN = ../../../deploy/bin/
DEPLOY_LIB = ../../../deploy/lib/

VPATH = $(NET_PATH)/src
SUB_DIRS := $(foreach dir, $(VPATH), $(shell find $(dir) -maxdepth 5 -type d))
DIRS := $(SUB_DIRS)


INC := $(INC) \
       -I $(3PARTY_PATH)/protobuf/src \
       -I $(3PARTY_PATH)/protobuf/build/_deps/absl-src \
       -I $(3PARTY_PATH)/include \
       -I $(3PARTY_PATH)/include/mariadb \
       -I $(3PARTY_PATH)/include/mongoc -I $(3PARTY_PATH)/include/bson \
       -I $(3PARTY_PATH)/include/libev \
       -I $(UTIL_PATH)/src -I $(UTIL_PATH)/src/Util \
       -I $(NET_PATH)/include \
       -I $(NET_PATH)/src 


LDFLAGS := $(LDFLAGS) -D_LINUX_OS_ \
           -L$(UTIL_PATH)/lib -lUtil \
           -L$(3PARTY_PATH)/protobuf/build \
           -L$(3PARTY_PATH)/protobuf/build/third_party/utf8_range \
           -L$(3PARTY_PATH)/lib -lmariadb \
           -L$(3PARTY_PATH)/lib -lhiredis_vip \
           -L$(3PARTY_PATH)/lib -lcryptopp \
           -L$(3PARTY_PATH)/lib -lprotobuf \
           -L$(3PARTY_PATH)/protobuf/build/third_party/utf8_range -lutf8_validity \
           $(ABSL_LINK) \
           -L$(3PARTY_PATH)/lib -llog4cplus \
           -L$(3PARTY_PATH)/lib -lev \
           -L$(3PARTY_PATH)/lib -ljemalloc \
           -L$(3PARTY_PATH)/lib -lcares \
           -L$(3PARTY_PATH)/lib -lcurl \
           -L$(3PARTY_PATH)/lib -lmongoc2 -L$(3PARTY_PATH)/lib -lbson2 \
           -L$(3PARTY_PATH)/lib -lleveldb \
           -L$(SYSTEM_LIB_PATH) -lpthread \
           -L$(SYSTEM_LIB_PATH) -lz -lc -ldl -lrt -lssl

SUB_INCLUDE = cmd step session labor codec protocol storage
COMM_PATH = $(NET_PATH)/src/cmd \
            $(NET_PATH)/src/step \
            $(NET_PATH)/src/session \
            $(NET_PATH)/src/labor \
            $(NET_PATH)/src/protocol \
            $(NET_PATH)/src/storage
CPP_SRCS = $(foreach dir, $(DIRS), $(wildcard $(dir)/*.cpp))
CC_SRCS = $(foreach dir, $(DIRS), $(wildcard $(dir)/*.cc))
C_SRCS = $(foreach dir, $(DIRS), $(wildcard $(dir)/*.c))
COMM_CPP_SRCS = $(foreach dir, $(COMM_PATH), $(wildcard $(dir)/*.cpp))
COMM_CC_SRCS = $(foreach dir, $(COMM_PATH), $(wildcard $(dir)/*.cc))
COMM_C_SRCS = $(foreach dir, $(COMM_PATH), $(wildcard $(dir)/*.c))
OBJS = $(patsubst %.cpp,%.o,$(CPP_SRCS)) $(patsubst %.c,%.o,$(C_SRCS)) $(patsubst %.cc,%.o,$(CC_SRCS))
COMM_OBJS = $(patsubst %.cpp,%.o,$(COMM_CPP_SRCS)) $(patsubst %.c,%.o,$(COMM_C_SRCS)) $(patsubst %.cc,%.o,$(COMM_CC_SRCS))

COMPILE_TARGETS = libNet.so Hello
CORE_TARGETS = 

all:$(COMPILE_TARGETS)
	@for target in $(ORTHER_TARGETS);do cp -vf Hello $$target;install -v $$target ${DEPLOY_BIN} ;done
	@for target in $(CORE_TARGETS);do cp -vf Hello $$target;install -v $$target ${DEPLOY_BIN} ;done

Hello:$(OBJS)
	$(CXX) $(CXXFLAG) $(UNITTEST) -o $@ $(OBJS) $(LDFLAGS) $(INC)
	echo "try to install $@"
	test  -d ${DEPLOY_BIN} && install -v $@ ${DEPLOY_BIN}
	
libNet.so: $(COMM_OBJS)
	$(CXX) $(UNITTEST) -fPIC -rdynamic -shared -g -o $@ $^ $(LDFLAGS)
	@for dir in $(SUB_INCLUDE); do mkdir -p $(NET_PATH)/include/$$dir; cp $(NET_PATH)/src/$$dir/*.hpp $(NET_PATH)/include/$$dir/ >> /dev/null 2>&1; cp $(NET_PATH)/src/$$dir/*.h $(NET_PATH)/include/$$dir/ >> /dev/null 2>&1; done
	cp -f $(NET_PATH)/src/*.hpp $(NET_PATH)/include/
	cp -f $@ $(NET_PATH)/lib/
	test  -d ${DEPLOY_LIB} && install -v $@ ${DEPLOY_LIB}

%.o:%.cpp
	$(CXX) $(INC) $(CPPFLAGS) $(CFLAGS) $(DEFINE_SERVER) $(UNITTEST) -c -o $@ $< $(LDFLAGS)
%.o:%.cc
	$(CXX) $(INC) $(CPPFLAGS) $(UNITTEST) -c -o $@ $< $(LDFLAGS)
%.o:%.c
	$(CC) $(INC) $(CFLAGS) $(UNITTEST) -c -o $@ $< $(LDFLAGS)
clean:
	rm -f $(OBJS)
	echo "del $(TARGET) $(COMPILE_TARGETS) $(ORTHER_TARGETS)"
	rm -f $(TARGET) $(COMPILE_TARGETS) $(ORTHER_TARGETS)
        
        
